### PR TITLE
fix(daemon): stop workspace AGENTS.md sync watcher loop

### LINKED ISSUE #337: Workspace AGENTS.md sync loop: missing content-check guard causes infinite watcher cycle
## Bug

After session-end synthesis writes identity files (SOUL.md, IDENTITY.md, INTENTIONS.md), the watcher triggers `syncAgentWorkspace()` which writes `AGENTS.md` to `agents/<name>/workspace/`. This write triggers the watcher again, creating an infinite loop that fires every ~2 seconds indefinitely.

## Reproduction

1. Run a session with identity synthesis enabled (pipelineV2 with command provider)
2. End the session — synthesis writes SOUL.md, IDENTITY.md, INTENTIONS.md
3. Watcher fires → `syncAgentWorkspace()` writes `agents/claude-code/workspace/AGENTS.md`
4. Watcher fires again (workspace dir is not in ignore list) → sync writes again → infinite loop

Observed in logs:
```
23:50:11 INFO [sync]    Synced to openclaw:claude-code {"target":".../workspace/AGENTS.md"}
23:50:13 INFO [sync]    Synced to openclaw:claude-code {"target":".../workspace/AGENTS.md"}
23:50:15 INFO [sync]    Synced to openclaw:claude-code {"target":".../workspace/AGENTS.md"}
// ...repeats every 2s indefinitely until daemon restart
```

## Root cause

`syncAgentWorkspace()` writes unconditionally:

```js
// line ~108300 in dist/daemon.js
const composed = base + agentIdentity + sharedIdentity;
mkdirSync(workspaceDir, { recursive: true });
writeFileSync(join(workspaceDir, "AGENTS.md"), composed);  // <-- no content check
```

The guard pattern already exists 10 lines below for `SIGNET-ARCHITECTURE.md`:

```js
// line ~108311
const existing = existsSync(archPath) ? readFileSync(archPath, "utf-8") : "";
if (existing !== archContent) {
  writeFileSync(archPath, archContent);
}
```

Additionally, `watcher-ignore.ts` excludes `.db-wal`, `.db-shm`, `.db-journal`, and predictor checkpoints, but does **not** exclude `agents/*/workspace/`.

## Suggested fix

Either:
1. Add content-check guard before writing workspace AGENTS.md (consistent with SIGNET-ARCHITECTURE.md pattern)
2. Add `agents/*/workspace/` to the watcher ignore list

Option 1 is more defensive — it prevents unnecessary disk I/O even if triggered by other watchers.

## Environment

- signet v0.77.0
- macOS 15.4 (Darwin 25.3.0)
- Bun runtime (daemon)

### PR DESCRIPTION
**Pull request by aaf2tbz**
## Summary
Fixes an infinite sync/watch loop from generated `~/.agents/agents/*/workspace/AGENTS.md` writes retriggering the daemon watcher every debounce cycle.

Closes #337.

## Changes
- Added `writeFileIfChanged(path, content)` utility in `packages/daemon/src/file-sync.ts`.
- Updated `syncAgentWorkspaces()` to write workspace `AGENTS.md` only when content changes.
- Updated watcher ignore matcher to ignore generated per-agent workspace `AGENTS.md` paths.
- Reused `writeFileIfChanged()` in `ensureArchitectureDoc()` for consistency.
- Added regression tests for the no-op write guard and workspace ignore behavior.

## Type
- [ ] `feat` — new user-facing feature (bumps minor)
- [x] `fix` — bug fix
- [ ] `refactor` — restructure without behavior change
- [ ] `chore` — build, deps, config, docs
- [ ] `perf` — performance improvement
- [ ] `test` — test coverage

## Packages affected
- [ ] `@signet/core`
- [x] `@signet/daemon`
- [ ] `@signet/cli` / dashboard
- [ ] `@signet/sdk`
- [ ] `@signet/connector-*`
- [ ] `@signet/web`
- [ ] `predictor`
- [ ] Other:

## Screenshots
N/A (no UI changes)

## PR Readiness (MANDATORY)
- [x] Spec alignment validated (`INDEX.md` + `dependencies.yaml`)
- [x] Agent scoping verified on all new/changed data queries
- [x] Input/config validation and bounds checks added
- [x] Error handling and fallback paths tested (no silent swallow)
- [x] Security checks applied to admin/mutation endpoints
- [x] Docs updated for API/spec/status changes
- [x] Regression tests added for each bug fix
- [x] Lint/typecheck/tests pass locally

## Migration Notes (if applicable)
- [ ] Migration is idempotent
- [x] Daemon Rust parity reviewed or explicitly N/A
- [ ] Rollback / compatibility note included in PR description

Notes: N/A — no DB migrations, no Rust daemon behavior changed.

## Testing
- [x] `bun test` passes
- [ ] `bun run typecheck` passes
- [ ] `bun run lint` passes
- [ ] Tested against running daemon
- [ ] N/A

Validation run:
- `bun test packages/daemon/src/watcher-ignore.test.ts packages/daemon/src/file-sync.test.ts`
- `bunx @biomejs/biome check packages/daemon/src/watcher-ignore.ts packages/daemon/src/watcher-ignore.test.ts packages/daemon/src/file-sync.ts packages/daemon/src/file-sync.test.ts`

## AI disclosure
- [ ] No AI tools were used in this PR
- [x] AI tools were used (see `Assisted-by` tags in commits)

## Notes
This applies both requested mitigations:
1. content-check guard before workspace AGENTS.md writes,
2. watcher ignore for generated workspace AGENTS.md.

### CODE REVIEW

**Comment by PR-Reviewer-Ant** [comment]
Hi @aaf2tbz - I'm an automated code reviewer powered by [pr-reviewer](https://github.com/NicholaiVogel/pr-reviewer). I'm taking a look at the fixes in `fix(daemon): stop workspace AGENTS.md sync watcher loop` (commit `a2012a0a`) now and I'll follow up shortly with feedback.

File: packages/daemon/src/watcher-ignore.ts [hunk 1]
```diff
@@ -15,11 +15,17 @@ export function createAgentsWatcherIgnoreMatcher(agentsDir: string): (path: stri
 	const configuredPredictorCheckpoint = resolveForComparison(
 		resolvePredictorCheckpointPath(loadMemoryConfig(agentsDir).pipelineV2.predictor),
 	);
+	const agentRoot = resolveForComparison(join(agentsDir, "agents"));
 	const ignoredPaths = new Set([defaultPredictorCheckpoint, configuredPredictorCheckpoint]);
 
 	return (path: string): boolean => {
 		const normalizedPath = resolveForComparison(path);
```
Comment (PR-Reviewer-Ant) [inline packages/daemon/src/watcher-ignore.ts:29]: The new matcher is broader than the PR description. `normalizedPath.endsWith("AGENTS.md")` combined with `agentSegments[1] === "workspace"` ignores any `AGENTS.md` anywhere under `<agent>/workspace/**`, not just the generated `<agent>/workspace/AGENTS.md`. That can suppress legitimate watcher events for nested project files such as `<agent>/workspace/my-project/AGENTS.md`. The check should require the exact 3-segment shape `<agent>/workspace/AGENTS.md`.

File: packages/daemon/src/daemon.ts [hunk 2]
```diff
@@ -10404,8 +10405,10 @@ function syncAgentWorkspaces(agentsDir: string): void {
 			const composed = base + agentIdentity + sharedIdentity;
```
Comment (PR-Reviewer-Ant) [inline packages/daemon/src/daemon.ts:10405]: This changes `@signet/daemon` behavior, but the PR does not include the corresponding `packages/daemon-rs/` update required by the repo's Rust parity rule. Leaving the shadow rewrite on the old behavior risks divergence logs and inconsistent behavior between the JS daemon and the Rust shadow path.

**Review by PR-Reviewer-Ant — DISMISSED** [review]
> Automated review by [pr-reviewer](https://github.com/NicholaiVogel/pr-reviewer) | model: gpt-5.4 | commit: `a2012a0a`

[Automated Review] Found one blocking logic regression in the new watcher ignore rule and one parity gap against the repository's daemon/daemon-rs contract.

**Confidence:** Medium [sufficient_diff_evidence, targeted_context_included, missing_runtime_repro] - The overbroad ignore condition is directly visible in packages/daemon/src/watcher-ignore.ts: it matches any path under <agent>/workspace/** ending in AGENTS.md, while the PR description claims to ignore only the generated <agent>/workspace/AGENTS.md file. The daemon parity issue is also explicit from the repo contract included in the prompt: this PR changes daemon behavior but includes no corresponding packages/daemon-rs update. I could not run the daemon or watcher loop locally because the provided workspace snapshot does not include the full repository checkout.

**Comment by PR-Reviewer-Ant** [comment]
Hi @aaf2tbz - I'm an automated code reviewer powered by [pr-reviewer](https://github.com/NicholaiVogel/pr-reviewer). I'm taking a look at the fixes in `fix(daemon): stop workspace AGENTS.md sync watcher loop` (commit `25a1064c`) now and I'll follow up shortly with feedback.

**Comment by aaf2tbz** [comment]
Implemented the requested approach (both mitigations + both test tracks):

- Added content-change guard before writing `agents/*/workspace/AGENTS.md`.
- Added watcher ignore for generated `agents/*/workspace/AGENTS.md`.
- Added new guard utility tests (`file-sync.test.ts`).
- Extended watcher-ignore tests for workspace path behavior.

Commit: `25a1064c`

File: packages/daemon/src/watcher-ignore.ts (hunk 1 above)
Comment (PR-Reviewer-Ant) [inline packages/daemon/src/watcher-ignore.ts:29]: The new ignore logic uses `normalizedPath.startsWith(agentRoot)` without enforcing a path-segment boundary. That means paths like `<agentsDir>/agents-backup/foo/workspace/AGENTS.md` will be misclassified as generated workspace files and ignored, even though they are outside `agents/<agent>/workspace/AGENTS.md`. This diverges from the PR description and can hide legitimate file changes. Check for `agentRoot + path.sep` (or compare parsed segments) before slicing.

**Review by PR-Reviewer-Ant — COMMENTED** [review]
> Automated review by [pr-reviewer](https://github.com/NicholaiVogel/pr-reviewer) | model: gpt-5.4 | commit: `25a1064c`

[Automated Review] Found one correctness issue in the new watcher ignore matcher.
The no-op write guard does address the write-side half of the loop described in the PR, but the new ignore rule is broader than the PR description claims and can suppress unrelated paths.

**Confidence:** Medium [sufficient_diff_evidence, targeted_context_included, missing_runtime_repro] - The new matcher uses a plain prefix check (`normalizedPath.startsWith(agentRoot)`) and then slices the string without a path-boundary check. From the diff alone, that will also treat sibling directories such as `<agentsDir>/agents-backup/.../workspace/AGENTS.md` as if they were under `<agentsDir>/agents/...`, which broadens the ignore scope beyond generated per-agent workspaces. I did not reproduce this in a running daemon because only the PR context and diff were provided.

**Review by PR-Reviewer-Ant — COMMENTED** [review]
> Automated review by [pr-reviewer](https://github.com/NicholaiVogel/pr-reviewer) | model: gpt-5.4 | commit: `144f8ba7`

[Automated Review] No new issues found in the incremental changes; ready for human review.
The original PR claim about breaking the AGENTS.md watcher loop is still supported by the write-on-change guard and ignore-path tests, and the newly added update-install verification logic is consistent with the stated behavior in the added tests.

**Confidence:** Medium [sufficient_diff_evidence, targeted_context_included, missing_runtime_repro] - The review covered the provided PR description, full changed-file contents for the watcher-loop fix, and the incremental diff adding update-version verification. The new update-system logic now validates `targetVersion`, pins installs to an exact version when provided, and verifies the installed package version before setting `pendingRestartVersion`, which matches the added tests. I did not have a runnable repository snapshot or daemon/runtime trace to exercise package-manager-specific install flows end to end.

File: packages/daemon/src/watcher-ignore.ts (hunk 1 above)
Comment (aaf2tbz) [reply packages/daemon/src/watcher-ignore.ts:29]: Good catch — fixed in `67529a7d`. The matcher now requires the exact `<agent>/workspace/AGENTS.md` shape (`agentSegments.length === 3`) so nested `workspace/**/AGENTS.md` files are no longer ignored. Added regression expectations in `watcher-ignore.test.ts` for the nested-path case.

File: packages/daemon/src/daemon.ts (hunk 2 above)
Comment (aaf2tbz) [reply packages/daemon/src/daemon.ts:10405]: Followed up on parity here: this change is limited to JS daemon-only workspace sync/watcher code (`syncAgentWorkspaces` + `createAgentsWatcherIgnoreMatcher`). There is currently no corresponding workspace AGENTS sync/watcher path in `packages/daemon-rs`, so parity is N/A for this specific behavior change.

File: packages/daemon/src/watcher-ignore.ts (hunk 1 above)
Comment (aaf2tbz) [reply packages/daemon/src/watcher-ignore.ts:29]: Fixed in `67529a7d`. I replaced the raw `startsWith` + slice logic with `relative(root, target)` bounds checking, so sibling paths like `agents-backup/**` are not misclassified as being under `agents/**`. Added a regression test for the `agents-backup` case as well.

**Review by PR-Reviewer-Ant — COMMENTED** [review]
> Automated review by [pr-reviewer](https://github.com/NicholaiVogel/pr-reviewer) | model: gpt-5.4 | commit: `67529a7d`

[Automated Review] No new issues found in the current diff; ready for human review.

**Confidence:** High [sufficient_diff_evidence, targeted_context_included] - The latest diff directly addresses the previously flagged watcher-scope bugs by replacing the prefix-based path check with a root-bounded relative-path check and by narrowing the ignore rule to exactly `<agentsDir>/agents/<agent>/workspace/AGENTS.md`. The added tests cover both the nested-workspace false positive and the `agents-backup` sibling-path false positive.
