### PR TITLE
fix: ignore generated MEMORY backup markdown files

### LINKED ISSUE #451: File watcher ingests MEMORY.md backup files, creating thousands of duplicate chunk memories
## Bug Description

The file watcher in the Signet daemon ingests `MEMORY.backup-*.md` files from the `memory/` directory, creating duplicate chunk memories every time `MEMORY.md` is auto-regenerated.

## Root Cause

Two built-in features collide:

1. **MEMORY.md auto-generation** creates timestamped backup files (e.g., `MEMORY.backup-2026-03-31T21-17-05.md`)
2. **File watcher** matches `**/*.md` and ingests all markdown files in the agents directory, including these backups

The watcher does not exclude `*.backup-*` patterns, so every MEMORY.md refresh produces ~17 new chunk memories from the backup file. Over days, this compounds into tens of thousands of junk memories.

## Impact

In our case:
- **21,682 chunk memories** created from backup file ingestion (source_type = `chunk`)
- **39,353 total failed extractions** (partially due to volume + missing API key)
- Daemon pegged at 100% CPU trying to process the backlog
- 1.5GB database inflated with redundant content
- Nearly all chunk content is unique (39,351 unique out of 39,353) because each backup has slightly different timestamps/content — so deduplication does not catch them

## Evidence

```
# From daemon logs — watcher ingesting backup files:
[watcher] Ingested memory file {"path":"~/.agents/memory/MEMORY.backup-2026-03-31T21-17-05.md","chunks":17,"sections":16}
[watcher] Ingested memory file {"path":"~/.agents/memory/MEMORY.backup-2026-03-31T20-28-38.md","chunks":17,"sections":16}
[watcher] Ingested memory file {"path":"~/.agents/memory/MEMORY.backup-2026-03-31T10-44-42.md","chunks":17,"sections":16}

# Database stats:
sqlite> SELECT source_type, COUNT(*) FROM memories WHERE extraction_status = 'failed' GROUP BY source_type;
chunk|21682
openclaw-memory-log|17551
manual|120
```

## Suggested Fix

1. Add `*.backup-*` (and similar patterns like `*.bak-*`, `*.pre-*`) to the watcher's default ignore list alongside `.git` and `node_modules`
2. Alternatively, support a `.signetignore` file for user-configurable exclusions
3. Consider content-hash deduplication at the watcher level before creating chunk memories — if the sections are substantially similar to existing chunks, skip ingestion

## Environment

- signet v0.91.12
- macOS (arm64)
- Embedding: ollama/nomic-embed-text
- Extraction: openrouter (Gemini endpoint)

## Steps to Reproduce

1. Start signet daemon with file watcher enabled (default)
2. Let MEMORY.md auto-regenerate a few times (or manually trigger with `signet remember` calls)
3. Check `ls ~/.agents/memory/MEMORY.backup-*` — multiple backup files exist
4. Query: `sqlite3 ~/.agents/memory/memories.db "SELECT source_type, COUNT(*) FROM memories GROUP BY source_type;"` — chunk count grows with each backup

### PR DESCRIPTION
**Pull request by NicholaiVogel**
## Summary
Prevent generated `MEMORY.*-*.md` backup files from being re-ingested as memories.

## Context
`writeProjection()` writes timestamped backup files into `memory/` when refreshing `MEMORY.md`. The daemon watcher and startup importer treat markdown files in that directory as ingestible memory content, so those generated backups could create duplicate chunk memories and extraction backlog noise.

## Changes
- add a `MEMORY_BACKUP_FILENAME_RE` guard alongside the existing artifact filename filter
- skip generated `MEMORY.backup-*`, `MEMORY.bak-*`, and `MEMORY.pre-*` files before reading or chunking markdown content
- extend the regression tests to cover positive and negative backup filename cases while preserving the existing artifact coverage

## Testing
- `bun test packages/daemon/src/memory-ingest-filter.test.ts`
- `bun test packages/daemon/src/watcher-ignore.test.ts`
- `bunx @biomejs/biome check packages/daemon/src/memory-ingest-filter.test.ts`
- `bun run build` (from `packages/daemon`)

## Notes
- `bunx tsc -p packages/daemon/tsconfig.json --noEmit` still reports pre-existing unrelated typecheck failures in the daemon package and was not used as a passing gate for this fix.

## Links
- Closes #451

### CODE REVIEW

**Comment by BusyBee3333** [comment]
Hi @NicholaiVogel - I'm an automated code reviewer powered by [pr-reviewer](https://github.com/NicholaiVogel/pr-reviewer). I'm taking a look at the fixes in `fix: ignore generated MEMORY backup markdown files` (commit `253d9880`) now and I'll follow up shortly with feedback.

**Comment by PR-Reviewer-Ant** [comment]
Hi @NicholaiVogel - I'm an automated code reviewer powered by [pr-reviewer](https://github.com/NicholaiVogel/pr-reviewer). I'm taking a look at the fixes in `fix: ignore generated MEMORY backup markdown files` (commit `253d9880`) now and I'll follow up shortly with feedback.

File: packages/daemon/src/daemon.ts [hunk 1]
```diff
@@ -11235,13 +11235,16 @@ function chunkMarkdownHierarchically(
 // These are already distilled and inserted directly into the DB —
 // re-ingesting them through the chunker creates noisy duplicates.
 export const ARTIFACT_FILENAME_RE = /--(?:summary|transcript|compaction|manifest)\.md$/;
+export const MEMORY_BACKUP_FILENAME_RE = /^MEMORY\.(?:backup|bak|pre)-.+\.md$/;
```
Comment (PR-Reviewer-Ant) [inline packages/daemon/src/daemon.ts:11238]: The PR description says both the daemon watcher and startup importer have this re-ingestion bug, and both are fixed. The fix in `ingestMemoryMarkdown` is the right place if both paths call this function. However, `watcher-ignore.test.ts` is listed in the testing section but has no changes in the diff. If the watcher has its own early file-filter (e.g., a glob deny-list or a per-event skip check) that runs *before* calling `ingestMemoryMarkdown`, backup files that land on that early path would not be covered. Please confirm the watcher reaches `ingestMemoryMarkdown` for all `.md` files under `memory/` without a separate skip layer, or add the guard there too.

**Review by PR-Reviewer-Ant — COMMENTED** [review]
> Automated review by [pr-reviewer](https://github.com/NicholaiVogel/pr-reviewer) | model: claude-sonnet-4-6 | commit: `253d9880`

Automated bot review (pr-reviewer): Clean, minimal fix. One low-confidence gap worth a human follow-up.

**Confidence:** Medium [sufficient_diff_evidence, missing_cross_module_context] - The regex, guard placement in ingestMemoryMarkdown, and test coverage are all verifiable from the diff. The one gap — whether the daemon watcher has an independent file-skip layer that also needs the new guard — cannot be resolved from the diff alone, because watcher-ignore.test.ts appears in the PR's test command list but shows zero diff changes and the watcher's call path to ingestMemoryMarkdown is not visible here.
