### PR TITLE
fix: distinguish session-start timeouts from offline fallback

### LINKED ISSUE #343: CLI hook session-start: hardcoded 5s fetch timeout causes false 'daemon offline' fallback
## Summary

The `signet hook session-start` CLI command uses `fetchFromDaemon()` which has a hardcoded 5000ms timeout (`AbortSignal.timeout(timeout || 5000)` in `createDaemonClient()`). When the daemon's session-start handler is slow (e.g., Ollama cold start for recall/hints), the fetch times out and the CLI falls back to static identity with `[signet: daemon offline — running with static identity]` — even though the daemon is healthy.

The Claude Code hook wrapper timeout (`settings.json → hooks.SessionStart.timeout`) is set higher (8000ms+) but is irrelevant because the CLI's internal fetch timeout fires first.

## Environment

- signetai v0.77.0
- macOS Apple Silicon (M2)
- Daemon running under Bun
- LLM provider: Ollama qwen3:4b (cold start takes ~30s)

## Steps to Reproduce

1. Stop Ollama or let it go cold
2. Start a new Claude Code session with Signet hooks configured
3. The session-start hook fires, CLI fetches from daemon
4. Daemon calls Ollama for recall — Ollama cold starts (~30s)
5. CLI fetch times out at 5s → falls back to static identity
6. User sees `[signet: daemon offline — running with static identity]` despite daemon running

## Expected Behavior

The CLI should respect a configurable timeout for the session-start fetch, since this is the most latency-sensitive hook (involves recall + optional hints).

## Suggested Fix

In `createDaemonClient()`, replace:
```js
signal: AbortSignal.timeout(timeout || 5000)
```

With:
```js
signal: AbortSignal.timeout(timeout || parseInt(process.env.SIGNET_FETCH_TIMEOUT || "15000", 10))
```

Or better: allow per-hook timeout configuration in `agent.yaml`.

## Workaround

Local patch applied to `dist/cli.js` — changes default to 15000ms with `SIGNET_FETCH_TIMEOUT` env var override. Breaks on `npm update`.

### PR DESCRIPTION
**Pull request by NicholaiVogel**
## Summary

Fixes the false "daemon offline" fallback during session-start by separating timeout failures from real reachability failures, raising the session-start timeout policy above the generic 5s read default, and applying the same behavior across the CLI and sibling runtime integrations.

Closes #343.

## Changes

- Added shared core helpers/constants for session-start timeout resolution and degraded static-identity banners
- Updated CLI daemon fetch handling to classify timeout/offline/http/invalid-json separately and use a session-start-specific timeout path
- Updated CLI session-start fallback messaging so timeout fallback is truthful instead of claiming the daemon is offline
- Broadened the same timeout/offline distinction to the OpenClaw adapter, OpenCode plugin, and Oh My Pi extension session-start paths
- Aligned generated Claude Code `SessionStart` hook timeout with the Signet session-start timeout policy (hook process timeout = fetch timeout + 2 s buffer, so Signet can return a graceful fallback before Claude Code kills the process)
- Added regression tests for CLI/core fallback behavior, OpenClaw timeout fallback, and OpenCode/Oh My Pi daemon-client classification
- Documented `SIGNET_SESSION_START_TIMEOUT` and legacy `SIGNET_FETCH_TIMEOUT` behavior in CLI/config docs

## Type

- [ ] `feat` — new user-facing feature (bumps minor)
- [x] `fix` — bug fix
- [ ] `refactor` — restructure without behavior change
- [ ] `chore` — build, deps, config, docs
- [ ] `perf` — performance improvement
- [ ] `test` — test coverage

## Packages affected

- [x] `@signet/core`
- [ ] `@signet/daemon`
- [x] `@signet/cli` / dashboard
- [ ] `@signet/sdk`
- [x] `@signet/connector-*`
- [ ] `@signet/web`
- [ ] `predictor`
- [x] Other: `@signetai/signet-memory-openclaw`, `@signet/opencode-plugin`, `@signet/oh-my-pi-extension`

## Screenshots

No UI changes.

## PR Readiness (MANDATORY)

- [x] Spec alignment validated (`INDEX.md` + `dependencies.yaml`)
- [x] Agent scoping verified on all new/changed data queries
- [x] Input/config validation and bounds checks added
- [x] Error handling and fallback paths tested (no silent swallow)
- [x] Security checks applied to admin/mutation endpoints
- [x] Docs updated for API/spec/status changes
- [x] Regression tests added for each bug fix
- [x] Lint/typecheck/tests pass locally

## Migration Notes (if applicable)

- [ ] Migration is idempotent
- [x] Daemon Rust parity reviewed or explicitly N/A
- [ ] Rollback / compatibility note included in PR description

## Testing

- [x] `bun test` passes
- [x] `bun run typecheck` passes
- [ ] `bun run lint` passes
- [ ] Tested against running daemon
- [ ] N/A

## AI disclosure

- [ ] No AI tools were used in this PR
- [x] AI tools were used (see `Assisted-by` tags in commits)

## Notes

- Targeted regression suite passes clean (25 tests, 0 failures):
  - `bun test packages/cli/src/lib/daemon.test.ts packages/cli/src/commands/hook.test.ts packages/core/src/__tests__/identity.test.ts packages/opencode-plugin/src/daemon-client.test.ts packages/oh-my-pi-extension/src/daemon-client.test.ts packages/adapters/openclaw/src/index.test.ts`
- Broad workspace `bun test` and `bun run typecheck` have pre-existing failures outside this PR's scope:
  - `@signet/connector-oh-my-pi` / `@signet/oh-my-pi-extension` fail typecheck on a missing `@types/node` definition (pre-existing, not introduced here)
  - ~220 unrelated test failures in the daemon scheduler and other packages (pre-existing)
- `bun run lint` has many pre-existing formatting issues unrelated to this branch; not introduced here
- No schema or migration changes; daemon Rust parity N/A (connector/plugin layer only)

### CODE REVIEW

**Comment by PR-Reviewer-Ant** [comment]
Hi @NicholaiVogel - I'm an automated code reviewer powered by [pr-reviewer](https://github.com/NicholaiVogel/pr-reviewer). I'm taking a look at the fixes in `fix: distinguish session-start timeouts from offline fallback` (commit `5cea0b66`) now and I'll follow up shortly with feedback.

**Comment by BusyBee3333** [comment]
Hi @NicholaiVogel - I'm an automated code reviewer powered by [pr-reviewer](https://github.com/NicholaiVogel/pr-reviewer). I'm taking a look at the fixes in `fix: distinguish session-start timeouts from offline fallback` (commit `5cea0b66`) now and I'll follow up shortly with feedback.

File: packages/opencode-plugin/src/index.ts [hunk 1]
```diff
@@ -143,23 +169,25 @@ export const SignetPlugin: Plugin = async ({ directory, client: oc }) => {
...
+		"/api/hooks/session-start",
+		{
+			harness: HARNESS,
+			project: directory,
+			agentId,
+			runtimePath: RUNTIME_PATH,
+		},
+		sessionStartTimeout(),
+	);
+	if (start.ok) {
```
Comment (PR-Reviewer-Ant) [inline packages/opencode-plugin/src/index.ts:183]: Blocking: this changes session-start behavior for OpenCode on daemon HTTP failures or invalid JSON. Before this PR, `client.post()` returned `null` for those cases and the `catch` path fell back to static identity, so the user still got degraded context. After this change, only `timeout` and `offline` trigger fallback; `http` and `invalid-json` now leave `sessionContext` empty. That diverges from the PR description ('applying the same behavior across ... sibling runtime integrations') and is a real regression for transient 5xx / malformed-response cases.

File: packages/connector-claude-code/src/index.ts [hunk 2]
```diff
@@ -65,6 +66,11 @@ export interface SessionEndResult {
 	memoriesExtracted: number;
 }
 
+function sessionStartHookTimeout(): number {
```
Comment (PR-Reviewer-Ant) [inline packages/connector-claude-code/src/index.ts:72]: Warning: the PR description and docs say generated Claude Code SessionStart hooks use the Signet session-start timeout policy/default (`15000`), but this implementation adds an extra 2000 ms. That means generated configs will default to 17000 ms, not 15000 ms, so the code does not actually match the documented policy it claims to align with.

File: packages/cli/src/commands/hook.ts [hunk 3]
```diff
@@ -43,21 +74,45 @@ export function registerHookCommands(program: Command, deps: HookDeps): void {
 					context: options.context,
 					sessionKey,
 				}),
+				timeout: SESSION_START_TIMEOUT_MS,
 			});
```
Comment (PR-Reviewer-Ant) [inline packages/cli/src/commands/hook.ts:79]: This changes Claude Code session-start from graceful degradation to a hard failure on transient daemon errors. `http` and `invalid-json` now `process.exit(1)`, while the sibling runtimes added in this PR still fall back to static identity for those cases. A temporary 502 or malformed response will now block the harness instead of preserving the previous degraded startup behavior, which also diverges from the PR's claim of applying the same behavior across integrations.

**Review by PR-Reviewer-Ant — COMMENTED** [review]
> Automated review by [pr-reviewer](https://github.com/NicholaiVogel/pr-reviewer) | model: gpt-5.4 | commit: `9ad5e273`

[Automated Review] I did not find new blocking correctness, security, or regression issues in the submitted diff; this looks ready for human review.

**Confidence:** Medium [sufficient_diff_evidence, targeted_context_included, missing_runtime_repro] - The diff cleanly threads the new session-start timeout policy through the CLI, Claude Code connector, OpenClaw adapter, OpenCode plugin, Oh My Pi extension, shared core helper, tests, and docs. The main behavioral claim in the PR description is reflected in code: timeout failures are now classified separately from reachability failures and the session-start path uses a dedicated timeout. I did not run the affected runtimes end-to-end against a live daemon or Claude Code/OpenCode/OpenClaw hosts, so confidence stops short of high.
