### PR TITLE
fix(mcp): expose pinned param in memory_store and memory_modify

### LINKED ISSUE #490: memory_store and memory_modify MCP tools don't expose pinned parameter
## Summary

The Signet daemon fully supports memory pinning at the database, REST API, and CLI levels, but the MCP tool schemas for `memory_store` and `memory_modify` do not expose the `pinned` parameter. Agents using the MCP interface have no way to pin memories.

### `memory_store` MCP tool accepts:
- `content` (required)
- `type`, `importance`, `tags`, `transcript`, `structured` (optional)
- ❌ No `pinned` parameter

### `memory_modify` MCP tool accepts:
- `id`, `reason` (required)
- `content`, `type`, `importance`, `tags` (optional)
- ❌ No `pinned` parameter

### What the daemon already supports:
- **DB column:** `memories.pinned INTEGER DEFAULT 0` (indexed: `idx_memories_pinned`)
- **REST API:** `POST /api/memory/remember` accepts `pinned: true` in body (memory-routes.ts ~line 394)
- **REST API:** `PATCH /api/memory/:id` accepts `pinned` via `parseModifyPatch()` (utils.ts ~line 860)
- **CLI:** `signet remember --critical` maps to `pinned: true`
- **Scoring:** `effectiveScore()` returns `1.0` for pinned memories (no decay)
- **Search:** `memory_search` MCP tool already exposes `pinned` as a read-only filter

The plumbing is complete — only the MCP tool input schemas are missing the field.

## Expected behavior

```typescript
// memory_store should accept pinned
signet_memory_store({
  content: "Never push to remote",
  type: "rule",
  importance: 1.0,
  tags: "git,constraint",
  pinned: true  // ← not currently accepted
})

// memory_modify should accept pinned
signet_memory_modify({
  id: "abc-123",
  reason: "Marking as critical per user constraint",
  pinned: true  // ← not currently accepted
})
```

## Impact

Agents following memory-first protocols (like [signet-first](https://github.com/Ostico/signet-first)) are instructed to pin user-stated hard constraints and critical procedures. Without `pinned` in the MCP schema, these memories decay at `0.95^days` like everything else.

Current workaround: `importance: 1.0` + tag `critical` — ranks the memory high but doesn't prevent decay.

## Suggested fix

In `packages/daemon/src/mcp/tools.ts`:

**1. `memory_store` inputSchema (~line 710):**
```typescript
pinned: z.boolean().optional().describe("Pin as critical — prevents decay, effectiveScore = 1.0"),
```

**2. Pass through to daemon fetch (~line 725):**
```typescript
body: { content, importance, pinned, transcript, structured }
```

**3. `memory_modify` inputSchema (~line 825):**
```typescript
pinned: z.boolean().optional().describe("Pin or unpin memory"),
```

The REST API handlers already accept `pinned` — this is purely a schema registration change.

## Environment

- Signet version: installed from npm (`signetai` global package)
- Daemon: running on port 3850
- MCP transport: stdio (`mcp-stdio.js`)

### PR DESCRIPTION
**Pull request by Ostico**
Closes #490

## Problem

The MCP tool schemas for `memory_store` and `memory_modify` did not include the `pinned` parameter. Agents using the MCP interface had no way to pin memories — they decayed at `0.95^days` like everything else, even when the agent protocol called for pinning critical constraints.

The REST API, database, CLI, and scoring already fully supported pinning. Only the MCP input schemas were missing the field.

## Changes

| File | What changed |
|---|---|
| `packages/daemon/src/mcp/tools.ts` | Added `pinned` to `memory_store` and `memory_modify` input schemas, handler destructuring, and fetch bodies |
| `packages/opencode-plugin/src/tools.ts` | Added `pinned` to `memory_store`, `memory_modify`, and `remember` alias (args, bodies, success message) |
| `packages/daemon-rs/crates/signet-daemon/src/mcp/tools.rs` | Added `pinned` to store/modify schemas, parsed in `exec_memory_store` handler, updated existing Rust test assertion |
| `packages/daemon/src/mcp/tools.test.ts` | Added 2 regression tests: `memory_store` and `memory_modify` pass `pinned: true` through to request body |

## PR checklist

- [x] Not spec-governed (narrow bug fix within existing contracts)
- [x] Agent scoping unchanged (pinned is orthogonal to scoping)
- [x] No new validation needed (`pinned` is `z.boolean().optional()`, defaults to `false`/omitted)
- [x] Error handling unchanged (existing fallback paths preserved)
- [x] No security surface change (pinned is a data attribute, not an auth gate)
- [x] No doc/API changes needed (`memory_search` already documents `pinned` as a filter — this PR makes write parity)
- [x] No publish manifest changes
- [x] Each fix has a regression test (2 new tests)
- [x] Lint, typecheck, and tests pass locally on changed files
- [x] Note: Rust daemon `memory_modify` handler is a stub (returns "not yet implemented" at line 344) — only the schema was updated, not the handler

## AI disclosure

This PR was authored with AI assistance per [AI_POLICY.md](https://github.com/Signet-AI/signetai/blob/main/AI_POLICY.md). All changes were human-reviewed and verified.

### CODE REVIEW

**Comment by PR-Reviewer-Ant** [comment]
Hi @Ostico - I'm an automated code reviewer powered by [pr-reviewer](https://github.com/NicholaiVogel/pr-reviewer). I'm taking a look at the fixes in `fix(mcp): expose pinned param in memory_store and memory_modify` (commit `2d1a92bc`) now and I'll follow up shortly with feedback.

File: packages/daemon-rs/crates/signet-daemon/src/mcp/tools.rs [hunk 1]
```diff
@@ -115,6 +116,7 @@ pub fn definitions() -> Vec<ToolDefinition> {
                     "content": { "type": "string", "description": "New content" },
```
Comment (PR-Reviewer-Ant) [inline packages/daemon-rs/crates/signet-daemon/src/mcp/tools.rs:116]: The `memory_modify` schema now advertises `pinned` as a supported field, but the handler for this tool is still a stub that unconditionally returns `'tool memory_modify not yet implemented in Rust daemon'` (see the match arm at line ~344). A caller that supplies `pinned: true` to the Rust daemon's `memory_modify` will receive an error, not a silent no-op — so no data is silently dropped — but the schema is now more specific than the implementation. The PR description explicitly acknowledges this; flagging here for human reviewer visibility only.

**Review by PR-Reviewer-Ant — COMMENTED** [review]
> Automated review by [pr-reviewer](https://github.com/NicholaiVogel/pr-reviewer) | model: claude-sonnet-4-6 | commit: `2d1a92bc`

[Automated Review — pr-reviewer bot] PR #491 adds the `pinned` parameter to MCP tool schemas for `memory_store` and `memory_modify` across the JS daemon, Rust daemon, and OpenCode plugin. Implementation is clean, tests are appropriate, and no correctness, security, or data-integrity issues were found in the changed code.

**Confidence:** High [sufficient_diff_evidence, targeted_context_included] - The diff is small and self-contained. Each changed path (schema addition, handler destructuring, body forwarding, test assertions) is fully visible. The Rust handler change at tools.rs:500 is verifiable against the surrounding exec_memory_store context. The JS handler change at tools.ts:714–728 and tools.ts:817–820 are directly traceable to their request bodies. Both regression tests in tools.test.ts are straightforward pass-through checks with deterministic mock state. No cross-module invariants are at risk because `pinned` is an orthogonal data attribute that does not affect scoping, auth, or retention logic in any path touched here.


Unmapped findings (not on changed lines):
- packages/opencode-plugin/src/tools.ts:196 - The `remember` alias now accepts and forwards `pinned`, but its success message (`Saved: ${args.content.slice(0, 50)}`) does not surface whether pinning was requested, unlike `memory_store` which returns `Memory saved (pinned) (id: …)`. Minor UX inconsistency — no correctness impact.

File: packages/daemon-rs/crates/signet-daemon/src/mcp/tools.rs (hunk 1 above)
Comment (Ostico) [reply packages/daemon-rs/crates/signet-daemon/src/mcp/tools.rs:116]: Already stated in the PR description:

- [x] Note: Rust daemon memory_modify handler is a stub (returns "not yet implemented" at line 344) — only the schema was updated, not the handler

Comment (PR-Reviewer-Ant) [inline packages/daemon-rs/crates/signet-daemon/src/mcp/tools.rs:116]: The `memory_modify` schema now advertises `pinned` as a supported field, but the handler (`memory_modify` arm in `execute`) remains a stub that unconditionally returns `'tool memory_modify not yet implemented in Rust daemon'`. An agent that calls `memory_modify` with `pinned: true` through the Rust daemon will receive a stub error regardless of the schema promise. The PR description discloses this explicitly, so this is not a regression — but a schema/behavior contract mismatch is in play until the handler is implemented.

**Review by PR-Reviewer-Ant — COMMENTED** [review]
> Automated review by [pr-reviewer](https://github.com/NicholaiVogel/pr-reviewer) | model: claude-sonnet-4-6 | commit: `e819d305`

[Automated Review — pr-reviewer bot] PR #491 incrementally adds a `(pinned)` indicator to the `remember` alias success message in `packages/opencode-plugin/src/tools.ts`. The change is cosmetic and correct. The one substantive concern from the prior review cycle — the Rust daemon `memory_modify` schema advertising `pinned` while the handler remains a stub — is unchanged and still open.

**Confidence:** High [sufficient_diff_evidence, targeted_context_included] - The incremental diff since sha=2d1a92bc is a single-line success-message change in the `remember` alias at opencode-plugin/src/tools.ts:191. It is a pure string-formatting guard (`args.pinned ? ' (pinned)' : ''`) with no logic path risk. The previously flagged Rust `memory_modify` stub mismatch is fully visible in tools.rs; no new lines in this diff affect it.

**Comment by NicholaiVogel** [comment]
@Ostico Thank you for the contribution! Disregard the PR-reviewer yapping about rust parity. Merging this :)
