### PR TITLE
fix(daemon): resolve event-loop starvation from synchronous I/O on large memory directories

### LINKED ISSUE #589: daemon: event-loop starvation from synchronous I/O on large memory directories
## Summary

The daemon becomes completely unresponsive (HTTP timeouts on `/health`, `/api/config`) after ~30-60 minutes of operation on workspaces with large memory directories (~13,580 files). The process stays alive (`R` state, 17% CPU, 495MB RSS) but the event loop is starved — no HTTP requests are served and log output stops flushing.

**This is a different bug from #587** (OOM crash-loop). RSS stays low; the daemon simply stops responding.

## Prior mitigation (PR #513)

PR #513 ("resolve FD exhaustion and event loop blocking") introduced two mitigations for this class of problem:

1. **`synthesis-render-worker.ts`** — moves `renderMemoryProjection()` off the main thread into a dedicated worker. However, when the worker is unavailable or crashes, the code falls back to synchronous rendering on the main thread (`hooks.ts:3896`), re-exposing the blocking.
2. **`startMemoryImportPoller()`** — wraps `importExistingMemoryFiles()` in a 30s interval with an in-flight guard to prevent overlap. However, the underlying function still runs synchronous I/O on the main thread without yielding, so each invocation blocks the event loop for the full duration of the scan.

These mitigations reduced the frequency of starvation but did not eliminate the root cause: **synchronous file I/O and tight loops on the main thread without yielding.**

## Observed symptoms

- `/health` and `/api/config` both timeout after 2+ minutes
- Process: PID alive, `R` state, 17% CPU, 495MB RSS, 772 FDs, 22 threads
- Last log entry: `reindexMemoryArtifacts completed` (13,580 files, 32ms) followed by `Starting scheduled synthesis` — then silence for 2+ hours
- Log stops flushing (same pattern as OOM but without memory growth)
- Workspace: 13,580 memory artifact files, 207MB transcript JSONL (149K lines), 1.3GB SQLite DB

## Root cause

Multiple synchronous code paths block the event loop without yielding. When synthesis fires (after idle gap), a cascade of sync I/O monopolizes the main thread:

1. Synthesis fires → `renderMemoryProjection()` → `reindexMemoryArtifacts()` blocks main thread
2. Memory import poller (30s interval) fires → `importExistingMemoryFiles()` queues behind it
3. Both operations compete for the event loop → HTTP starves → log can't flush

### Critical

| File | Line | Function | Problem |
|------|------|----------|---------|
| `memory-lineage.ts` | 714 | `reindexMemoryArtifacts()` | `readFileSync` + `statSync` × 13,580 files in a tight loop, zero yields. Called from main thread when synthesis worker is null (fallback in `hooks.ts:3896`). |
| `transcript-jsonl.ts` | 143 | `readRecords()` | `readFileSync` on entire 207MB JSONL, then tight `JSON.parse` loop on 149K lines, zero yields. |
| `daemon.ts` | 500 | `importExistingMemoryFiles()` | `readdirSync` on 13,580-file directory, then `ingestMemoryMarkdown()` per file sequentially. Runs every 30s via poller. |

### High

| File | Line | Function | Problem |
|------|------|----------|---------|
| `native-memory-sources.ts` | 78, 244 | `walkMarkdownFiles()` → `syncExisting()` | Recursive `readdirSync`, then `indexNativeMemoryFile()` per file, zero yields. |
| `hooks.ts` | 2181 | `stripUntrustedMetadata()` | Nested `while(true)` loops scanning metadata blocks, zero yields. |
| `pipeline/provider.ts` | 830 | SSE stream parser | Nested `while(true)` loops; inner loop processes multiple events per chunk without yielding. |
| `pipeline/summary-worker.ts` | 796 | `processChunked()` | `for` loop over transcript chunks without yielding between chunks. |

### Medium

| File | Line | Function | Problem |
|------|------|----------|---------|
| `single-flight-runner.ts` | 29 | `execute()` | `while(true)` loop runs `runOnce()` repeatedly without yields between attempts. |
| `transcript-jsonl.ts` | 248 | `acquireTranscriptFileLock()` | `while(true)` busy-wait with 10ms sleep; can spin 30+ seconds if lock is held. |

## The cascade

```
synthesis trigger (idle gap)
  → handleSynthesisRequest()
    → renderMemoryProjection()
      → reindexMemoryArtifacts()          ← readFileSync × 13,580 files, ZERO yields
        → parseFrontmatterDocument()
        → statSync()
        → upsertArtifactRow()             ← sync DB write per file
      → readTopMemories()
      → readThreadHeads()
      → buildLedger()

Meanwhile (30s poller):
  → importExistingMemoryFiles()           ← readdirSync on 13,580 files
    → ingestMemoryMarkdown() per file     ← readFileSync + DB write per file
```

Both run on the main thread. Neither yields. HTTP is completely starved.

## Suggested fixes

1. **`reindexMemoryArtifacts()`**: Make async, yield every N files with `await new Promise(r => setTimeout(r, 0))`
2. **`readRecords()`**: Stream the JSONL instead of `readFileSync` on 207MB; or yield every 1000 lines
3. **`importExistingMemoryFiles()`**: Make async with yields every 10 files; or move to worker thread
4. **`walkMarkdownFiles()` / `syncExisting()`**: Add yields every 10 directories/files
5. **`stripUntrustedMetadata()`**: Add yield every 100 iterations
6. **General**: Ensure `renderMemoryProjection()` always runs in the synthesis worker thread, never falls back to main thread sync — or make the fallback path async with yields

## Reproduction

Any workspace with ~10,000+ memory artifact files. Wait for synthesis trigger (idle gap) or memory import poller cycle. `/health` will stop responding.

## Environment

- Bun runtime
- ~13,580 memory files in `~/.agents/memory/`
- 207MB transcript JSONL (149K lines)
- 1.3GB SQLite DB
- 3,725+ session events per day

### PR DESCRIPTION
**Pull request by Ostico**
## Summary

Fixes #589. The daemon became completely unresponsive (`/health` timeouts for 2+ hours) on workspaces with ~13,580 memory files because `reindexMemoryArtifacts`, `importExistingMemoryFiles`, and `walkMarkdownFiles` ran synchronous `readFileSync`/`statSync`/`readdirSync` in tight loops without yielding. Converted all three to async with periodic yields, added concurrency guards, and added regression tests.

## Changes

- `async-yield.ts`: new `yieldEvery(N)` cooperative scheduling utility
- `daemon.ts`: `importExistingMemoryFiles` — `readdirSync` to async `readdir` + yield every 10 files
- `native-memory-sources.ts`: `walkMarkdownFiles` — sync recursive to async generator + yield every 20 files
- `memory-lineage.ts`: `reindexMemoryArtifacts` — async `readFile`/`stat` + yield every 50 files; per-agentId single-flight wrapper prevents concurrent interleaving
- `memory-lineage.ts`: `renderMemoryProjection` + `syncManifestRefs` — async to propagate
- `hooks.ts`: `fallbackToSync` made async; callers use `void fallbackToSync(...)`
- `synthesis-render-worker.ts`: queue/drain serialization replaces bare async callback (prevents concurrent renders)
- `hooks.test.ts`, `memory-lineage.test.ts`: all async calls awaited; concurrent reindex regression tests
- `synthesis-worker.test.ts`: concurrent render serialization test; timeout bump for real-DB fallback
- `event-loop-responsiveness.test.ts`: new — verifies max latency <200ms under 500-file reindex load
- `async-yield.test.ts`: new — unit tests for `yieldEvery`

## Type

- [ ] `feat` — new user-facing feature (bumps minor)
- [x] `fix` — bug fix
- [ ] `refactor` — restructure without behavior change
- [ ] `chore` — build, deps, config, docs
- [ ] `perf` — performance improvement
- [ ] `test` — test coverage

## Packages affected

- [ ] `@signet/core`
- [x] `@signet/daemon`
- [ ] `@signet/cli` / dashboard
- [ ] `@signet/sdk`
- [ ] `@signet/connector-*`
- [ ] `@signet/web`
- [ ] `predictor`
- [ ] Other:

## Screenshots

N/A — no UI changes.

## PR Readiness (MANDATORY)

- [x] Spec alignment validated (`INDEX.md` + `dependencies.yaml`) — aligns with `daemon-startup-responsiveness` planning spec
- [x] Agent scoping verified on all new/changed data queries — single-flight keyed by agentId
- [x] Input/config validation and bounds checks added — batch sizes clamped (10/20/50)
- [x] Error handling and fallback paths tested (no silent swallow) — async stat/readFile wrapped in try/catch
- [x] Security checks applied to admin/mutation endpoints — N/A, no new endpoints
- [x] Docs updated for API/spec/status changes — N/A, no API changes
- [x] Regression tests added for each bug fix — event-loop responsiveness, concurrent reindex, concurrent worker renders
- [x] Lint/typecheck/tests pass locally

## Testing

- [x] `bun test` passes (42 tests across 5 files, 0 fail)
- [x] `bun run typecheck` passes (0 new errors; 2 pre-existing on main)
- [x] `bun run lint` passes
- [x] Tested against running daemon — binary swap, 24+ min stable uptime, cold reindex of 13,637 files in ~25s (previously 2+ hours of starvation)
- [ ] N/A

## AI disclosure

- [ ] No AI tools were used in this PR
- [x] AI tools were used (see `Assisted-by` tags in commits)

## Notes

Remaining follow-ups not in this PR:
- Benchmark cold/warm render to validate or adjust the 30s parent timeout in `hooks.ts`
- `syncManifestRefs` still does sync file I/O inside the render path — may need yields for very large workspaces
- Other blocking paths from #589 (`readRecords`, `stripUntrustedMetadata`, SSE parser) are lower severity and tracked separately

### CODE REVIEW

**Comment by PR-Reviewer-Ant** [comment]
Hi @Ostico - I'm an automated code reviewer powered by [pr-reviewer](https://github.com/NicholaiVogel/pr-reviewer). I'm taking a look at the fixes in `fix(daemon): resolve event-loop starvation from synchronous I/O on large memory directories` (commit `41f78dc7`) now and I'll follow up shortly with feedback.

**Review by PR-Reviewer-Ant — COMMENTED** [review]
> Automated review by [pr-reviewer](https://github.com/NicholaiVogel/pr-reviewer) | model: gpt-5.3-codex | commit: `41f78dc7`

[Automated Review by pr-reviewer] I found one non-blocking correctness risk; the main starvation fix appears to match the PR description.

**Confidence:** Medium [sufficient_diff_evidence, targeted_context_included] - The diff clearly converts targeted hot paths to async + cooperative yields and updates call sites/tests accordingly. The remaining concern is directly visible in the new shared utility API and can affect future callers.

File: platform/daemon/src/async-yield.ts [hunk 1]
```diff
@@ -0,0 +1,11 @@
+export function yieldEvery(batchSize: number): () => Promise<void> {
```
Comment (PR-Reviewer-Ant) [inline platform/daemon/src/async-yield.ts:1]: `yieldEvery(batchSize)` accepts any number but does not validate bounds. If a future caller passes `NaN` (or a non-finite value), `count >= batchSize` never becomes true and the helper will never yield, potentially reintroducing event-loop starvation. Add an explicit guard (e.g., clamp to `>=1` finite integer or throw) to make this utility safe by contract.

Comment (NicholaiVogel) [reply platform/daemon/src/async-yield.ts:1]: Fixed in `61d9324e`. `yieldEvery` now normalizes the batch size to a finite positive integer, falling back to 1 for invalid values so future callers cannot accidentally disable yielding. Added regression coverage for NaN, Infinity, zero, negative, and fractional batch sizes.

File: platform/daemon/src/memory-lineage.ts [hunk 2]
```diff
@@ -711,9 +709,25 @@ export function deleteArtifactRowsForPath(path: string, agentId: string | null):
 	});
 }
 
-export function reindexMemoryArtifacts(agentId?: string): void {
+// Per-agentId single-flight: second callers await the first's result instead of interleaving.
+const reindexFlights = new Map<string, Promise<void>>();
+
```
Comment (PR-Reviewer-Ant) [inline platform/daemon/src/memory-lineage.ts:731]: Single-flight is keyed per scope (`agentId` or `*`), which still allows concurrent `reindexMemoryArtifacts()` (global) and `reindexMemoryArtifacts("some-agent")` runs. Those runs both mutate shared DB rows and shared manifest/cache maps and can interleave, reintroducing race behavior the PR is trying to prevent. Consider a stronger lock strategy (e.g., global lock plus scoped lock hierarchy, or making global lock exclude all scoped runs and vice versa).

**Review by PR-Reviewer-Ant — COMMENTED** [review]
> Automated review by [pr-reviewer](https://github.com/NicholaiVogel/pr-reviewer) | model: gpt-5.3-codex | commit: `61d9324e`

[Automated bot review by pr-reviewer] I found one concurrency correctness issue that can cause reindex interleaving despite the new single-flight guard.

**Confidence:** Medium [sufficient_diff_evidence, targeted_context_included, missing_cross_module_context] - The new single-flight map keys by exact `agentId` string (or `*`), so a scoped call and an unscoped call can still run concurrently and both mutate `memory_artifacts` and cache state. This is directly visible in the new `reindexMemoryArtifacts` implementation, but I cannot confirm all runtime callsites from the truncated context.

File: platform/daemon/src/memory-lineage.ts (hunk 2 above)
Comment (NicholaiVogel) [reply platform/daemon/src/memory-lineage.ts:731]: Fixed in `967c2eee`. Reindexing now keeps same-scope single-flight coalescing, but execution is serialized through a shared tail promise so unscoped/global runs and scoped runs cannot mutate artifact DB/cache state concurrently. Added coverage for concurrent global plus scoped calls.

**Review by PR-Reviewer-Ant — COMMENTED** [review]
> Automated review by [pr-reviewer](https://github.com/NicholaiVogel/pr-reviewer) | model: gpt-5.3-codex | commit: `967c2eee`

[Automated Review] I reviewed PR #596 as an automated bot reviewer (pr-reviewer); I did not find correctness, security, or data-integrity regressions in the supplied diff, and the implementation matches the PR description’s async/yield + serialization goals.

**Confidence:** Medium [sufficient_diff_evidence, targeted_context_included] - The core starvation paths called out in the PR description are concretely converted to async (`readdir`/`readFile`/`stat`) with cooperative yielding (`yieldEvery`) in `daemon.ts`, `memory-lineage.ts`, and `native-memory-sources.ts`; `renderMemoryProjection` propagation to async is consistently wired through worker and hook callsites; and regression tests were updated/added for async behavior and concurrent reindex/render serialization.

File: platform/daemon/src/memory-lineage.ts [hunk 3]
```diff
@@ -797,19 +834,22 @@ export function reindexMemoryArtifacts(agentId?: string): void {
...
+			await yielder();
 			continue;
 		}
 		const body = normalizeMarkdownBody(parsed.body);
 		if (!isValidArtifact(path, parsed.frontmatter, body)) {
 			deleteArtifactRowsForPath(path, scope);
 			cache.set(path, statKey);
 			changedPaths.add(path);
+			await yielder();
 			continue;
```
Comment (PR-Reviewer-Ant) [inline platform/daemon/src/memory-lineage.ts:863]: Uncaught race on second `stat(path)`: after successful async `stat` + `readFile`, the code does another `await stat(path)` for `mtimeMs` outside a try/catch. If the file is removed/renamed between awaits, this throws and aborts `reindexMemoryArtifacts` for the entire scope. Reuse the first stat result’s mtime (or guard this second stat) to keep reindex resilient under file churn.

**Review by PR-Reviewer-Ant — COMMENTED** [review]
> Automated review by [pr-reviewer](https://github.com/NicholaiVogel/pr-reviewer) | model: gpt-5.3-codex | commit: `709155d9`

[Automated Review] I found one reliability bug that can reintroduce stalled/failed reindex behavior under concurrent file churn; otherwise the PR largely matches its stated goals.

**Confidence:** High [sufficient_diff_evidence, targeted_context_included] - The new async reindex path in memory-lineage.ts performs a second uncaught stat() after prior awaited operations; if the file is deleted/rotated between those awaits, the promise rejects and aborts the whole reindex run. This is directly visible in the changed loop and is a concrete failure mode for large, actively changing memory directories.

File: platform/daemon/src/memory-lineage.ts (hunk 3 above)
Comment (NicholaiVogel) [reply platform/daemon/src/memory-lineage.ts:863]: Fixed in `89c641bb`. The reindex loop now keeps the first successful stat result and passes that `mtimeMs` into `upsertArtifactRow`, removing the second unguarded `stat(path)` after awaited reads. This keeps the run resilient if the file is removed or rotated after the initial stat/read window.

File: platform/daemon/src/memory-lineage.ts [hunk 4]
```diff
@@ -1504,11 +1545,11 @@ function renderIndexSection(indexBlock: string, base: ReadonlyArray<string>): st
 	return "";
```
Comment (PR-Reviewer-Ant) [inline platform/daemon/src/memory-lineage.ts:1589]: `syncManifestRefs` is now `async` but still performs synchronous manifest reads/writes through `loadManifest`/`saveManifest` (`readFileSync`/`writeFileSync`). On large workspaces this can still block the event loop during projection rendering, which partially diverges from the PR’s stated goal of resolving starvation from synchronous filesystem loops. Consider converting manifest read/write in this path to async I/O (or batching/yielding between sync operations) to fully align with the responsiveness fix.

**Review by PR-Reviewer-Ant — COMMENTED** [review]
> Automated review by [pr-reviewer](https://github.com/NicholaiVogel/pr-reviewer) | model: gpt-5.3-codex | commit: `9c19ae8d`

[Automated Review by pr-reviewer] I found one non-blocking but material divergence from the PR’s responsiveness goal.

**Confidence:** High [sufficient_diff_evidence, targeted_context_included] - The diff shows `syncManifestRefs` was made `async`, but it still calls synchronous file I/O via `loadManifest`/`saveManifest` (which use `readFileSync`/`writeFileSync`). This is directly visible in `memory-lineage.ts` and is relevant to the PR’s stated event-loop responsiveness objective.

File: platform/daemon/src/memory-lineage.ts (hunk 4 above)
Comment (NicholaiVogel) [reply platform/daemon/src/memory-lineage.ts:1589]: Fixed in `2e139dbf`. `syncManifestRefs` now uses async manifest read/write helpers for this projection path and yields every 20 manifest files, so render-time manifest ref updates no longer run as a synchronous filesystem loop. Kept the existing sync helpers in place for the other call sites.

**Review by PR-Reviewer-Ant — COMMENTED** [review]
> Automated review by [pr-reviewer](https://github.com/NicholaiVogel/pr-reviewer) | model: gpt-5.3-codex | commit: `2e139dbf`

[Automated Review] pr-reviewer found no blocking correctness or security issues in the provided diff; this is ready for human review.

**Confidence:** Medium [sufficient_diff_evidence, targeted_context_included] - The diff consistently propagates async conversion for the three stated hot paths (`reindexMemoryArtifacts`, `importExistingMemoryFiles`, `walkMarkdownFiles`), adds cooperative yields, and introduces serialization guards with regression tests for concurrent reindex/render behavior and event-loop responsiveness.


**Since my last review:**
- Fixed or likely addressed: 1
- Still blocking: 0
- Newly found: 0
- Suppressed due to human rebuttal/out-of-scope: 0
