### PR TITLE
fix(daemon): make writeImmutableArtifact idempotent for job retries

### LINKED ISSUE #534: fix(daemon): summary-worker attempts to overwrite immutable artifacts
**Signet version:** 0.102.4
**Environment:** Linux 6.8.0-110-generic, Node v22.22.1, Bun 1.3.12
**Related issues:** N/A

---

## Summary

The summary worker attempts to write a session summary artifact that already exists on disk. The `writeImmutableArtifact()` guard in `memory-lineage.ts` correctly refuses the mutation, but the worker treats this as a job failure instead of recognizing the artifact was already written successfully by a previous run.

---

## Observed Behavior

During normal daemon operation, the summary worker processes a session and attempts to write a summary artifact. When the artifact file already exists from a prior processing attempt, the immutability guard throws and the job fails:

```json
{
  "timestamp": "2026-04-20T11:47:46.902Z",
  "level": "error",
  "category": "summary-worker",
  "message": "Job failed",
  "data": {
    "error": "Refusing to mutate immutable artifact /home/user/.agents/memory/2026-04-13T13-59-42.147Z--zbhd2zcyehiklyts--summary.md"
  },
  "error": {
    "name": "Error",
    "message": "Refusing to mutate immutable artifact /home/user/.agents/memory/2026-04-13T13-59-42.147Z--zbhd2zcyehiklyts--summary.md",
    "stack": "Error: Refusing to mutate immutable artifact ...\n    at writeImmutableArtifact (/packages/daemon/src/memory-lineage.ts:466:13)\n    at writeSummaryArtifact (/packages/daemon/src/memory-lineage.ts:884:19)\n    at async processJob (/packages/daemon/src/pipeline/summary-worker.ts:604:33)\n    at async tick (/packages/daemon/src/pipeline/summary-worker.ts:1644:10)"
  }
}
```

Note: the artifact date (`2026-04-13`) is a week before the error (`2026-04-20`), confirming this is a retry of an already-completed job.

---

## Expected Behavior

The summary worker should check whether the artifact already exists before attempting to write it. If the artifact is already present, the worker should:
- Skip the write
- Log at DEBUG or INFO level that the artifact already exists
- Continue processing the remaining steps of the job (fact insertion, continuity scoring, etc.) or mark the job as already completed

The job should not fail.

---

## Steps to Reproduce

1. Start the daemon after it has been stopped for a while (queued summary jobs accumulate)
2. Let the summary worker drain its job queue
3. Observe that some jobs fail when they try to rewrite artifacts from sessions that were already summarized in a prior daemon run

The issue is most likely to appear after daemon restarts, when the job queue may contain entries for sessions whose artifacts were already written before the shutdown.

---

## Root Cause Analysis

The call chain is:

```
summary-worker.ts:604  processJob()
  → memory-lineage.ts:884  writeSummaryArtifact()
    → memory-lineage.ts:466  writeImmutableArtifact()  ← throws if file exists
```

`writeImmutableArtifact()` at line 466 correctly enforces immutability — once written, artifacts should never be overwritten. The problem is upstream: `processJob()` at line 604 does not check whether the artifact already exists before calling `writeSummaryArtifact()`.

The job queue likely persists across daemon restarts (stored in SQLite), so stale jobs that were partially or fully completed before a shutdown get re-processed. The fact insertion step (line 626) has its own idempotency (content hash uniqueness), but the artifact write step does not.

---

## Suggested Fix

At `summary-worker.ts:604`, before calling `writeSummaryArtifact()`:

```typescript
// Option A: Check existence before writing
const artifactPath = buildSummaryArtifactPath(sessionKey, timestamp);
if (await Bun.file(artifactPath).exists()) {
  logger.debug("summary-worker", "Summary artifact already exists, skipping write", { artifactPath });
} else {
  await writeSummaryArtifact(...);
}
```

Or in `writeImmutableArtifact()` itself:

```typescript
// Option B: Make writeImmutableArtifact idempotent
if (await Bun.file(path).exists()) {
  return; // Already written, nothing to do
}
```

Option B is safer as it makes all immutable artifact writes idempotent, but may mask unintended re-writes that should be investigated. Option A is more surgical and preserves the guard for unexpected cases.

---

## Impact

- Jobs are marked as failed and retried, wasting extraction resources on sessions that were already fully processed
- Dashboard and logs show spurious ERROR entries
- No data loss — the immutability guard prevents corruption
- Most visible after daemon restarts when stale jobs are drained

---

## Workaround

None needed for data integrity. The immutability guard works correctly. The error is cosmetic but noisy in logs and wastes extraction cycles on retries.

---

## Environment Details

- **Signet:** 0.102.4
- **OS:** Ubuntu, Linux 6.8.0-110-generic
- **Node:** v22.22.1
- **Bun:** 1.3.12
- **DB:** SQLite (bun:sqlite, WAL mode)
- **Date observed:** 2026-04-20

### PR DESCRIPTION
**Pull request by aaf2tbz**
## Summary

The summary worker fails when retrying a job whose artifact already exists on disk. `writeImmutableArtifact` throws when the content hash differs from the existing file, but this is expected on retries where the LLM may produce different summary text for the same session. Changed `writeImmutableArtifact` to return the existing path unconditionally when the file exists, making all artifact writes (summary, transcript, compaction) idempotent across daemon restarts and job retries.

Fixes #534

## Changes

- `packages/daemon/src/memory-lineage.ts`: Simplify `writeImmutableArtifact` existence check — return path immediately when file exists, removing the hash-mismatch throw
- `packages/daemon/src/memory-lineage.test.ts`: Add regression test verifying idempotent `writeSummaryArtifact` with different content produces same path and single DB row

## Type

- [ ] `feat` — new user-facing feature (bumps minor)
- [x] `fix` — bug fix
- [ ] `refactor` — restructure without behavior change
- [ ] `chore` — build, deps, config, docs
- [ ] `perf` — performance improvement
- [ ] `test` — test coverage

## Packages affected

- [ ] `@signet/core`
- [x] `@signet/daemon`
- [ ] `@signet/cli` / dashboard
- [ ] `@signet/sdk`
- [ ] `@signet/connector-*`
- [ ] `@signet/web`
- [ ] `predictor`
- [ ] Other: 

## Screenshots

N/A — no UI changes.

## PR Readiness (MANDATORY)

- [x] Spec alignment validated (`INDEX.md` + `dependencies.yaml`)
- [x] Agent scoping verified on all new/changed data queries
- [x] Input/config validation and bounds checks added
- [x] Error handling and fallback paths tested (no silent swallow)
- [x] Security checks applied to admin/mutation endpoints
- [x] Docs updated for API/spec/status changes
- [x] Regression tests added for each bug fix
- [x] Lint/typecheck/tests pass locally

## Migration Notes (if applicable)

N/A — no schema changes.

## Testing

- [x] `bun test` passes
- [x] `bun run typecheck` passes
- [x] `bun run lint` passes
- [ ] Tested against running daemon
- [ ] N/A

## AI disclosure

- [ ] No AI tools were used in this PR
- [x] AI tools were used (see `Assisted-by` tags in commits)

## Notes

The immutability guarantee is preserved — files are never overwritten. All 3 callers of `writeImmutableArtifact` (summary:800, transcript:759, compaction:841) handle the early return correctly. `isTerminalSummaryJobError` and `IMMUTABLE_ARTIFACT_ERROR_PREFIX` retained as safety net for any future paths that might produce this error.

### CODE REVIEW

**Comment by PR-Reviewer-Ant** [comment]
Hi @aaf2tbz - I'm an automated code reviewer powered by [pr-reviewer](https://github.com/NicholaiVogel/pr-reviewer). I'm taking a look at the fixes in `fix(daemon): make writeImmutableArtifact idempotent for job retries` (commit `043cb843`) now and I'll follow up shortly with feedback.

File: packages/daemon/src/memory-lineage.ts [hunk 1]
```diff
@@ -459,11 +459,7 @@ function writeImmutableArtifact(seed: ArtifactSeed): string {
 	const content = `${serializeFrontmatter(frontmatter)}\n${body}\n`;
 
 	if (existsSync(path)) {
-		const existing = parseFrontmatterDocument(readFileSync(path, "utf8"));
-		const existingHash = existing.frontmatter.content_sha256;
-		const nextHash = frontmatter.content_sha256;
-		if (existingHash === nextHash) return path;
-		throw new Error(`${IMMUTABLE_ARTIFACT_ERROR_PREFIX} ${path}`);
+		return path;
```
Comment (PR-Reviewer-Ant) [inline packages/daemon/src/memory-lineage.ts:472]: Blocking: `writeImmutableArtifact` now unconditionally trusts any existing file at the computed path. This removes the prior mismatch detection and allows silent acceptance of corrupted/tampered artifacts or unintended path collisions, which is a data-integrity regression. Idempotent retries should return existing content only after validating immutable invariants (at minimum kind/session/hash_scope/content_sha256) and fail when existing content is inconsistent.

**Review by PR-Reviewer-Ant — CHANGES_REQUESTED** [review]
> Automated review by [pr-reviewer](https://github.com/NicholaiVogel/pr-reviewer) | model: gpt-5.3-codex | commit: `043cb843`

[Automated Review] I am an automated bot review tool (pr-reviewer). The idempotency goal is mostly implemented, but the current change removes an integrity guard and can silently accept corrupted or colliding artifacts.

**Confidence:** High [sufficient_diff_evidence, targeted_context_included] - The changed logic in packages/daemon/src/memory-lineage.ts now returns early on any existing path without validating existing frontmatter/body hash. Previously this code compared content hashes and rejected mismatches. That is a direct, observable behavioral regression in integrity enforcement from the diff itself.
