### PR TITLE
fix(dashboard): show own-agent presence in readout

### LINKED ISSUE #568: Dashboard PROJECT/LAST SEEN render `--` — `/api/cross-agent/presence` defaults `include_self=false`
**Version:** 0.108.9 (latest)

## Symptom

Agent readout shows `PROJECT: --`, `LAST SEEN: --` even with active sessions and hooks correctly passing `--project "$(pwd)"`. SESSIONS count is correct (e.g. 3).

## Root cause

`registerCrossAgentPresence` in `daemon.js` defaults `includeSelf` to `false`:

```js
const includeSelf = parseOptionalBoolean(c2.req.query("include_self")) ?? false;
```

Dashboard queries `/api/cross-agent/presence` without `include_self=true`. Calling agent (`default`) is filtered out of its own presence list. All my sessions are agent `default`, so every session is filtered → empty list → `--`.

## Reproduction

```bash
# Empty:
curl 'http://localhost:3850/api/cross-agent/presence'
# {"sessions":[],"count":0}

# Full data present:
curl 'http://localhost:3850/api/cross-agent/presence?include_self=true'
# 5 sessions, each with project + lastSeenAt populated
```

`/api/sessions` returns sessions but lacks `project` field, so dashboard cannot fall back to it for the readout.

## Expected

Own-agent readout renders project + lastSeenAt for current sessions.

## Fix options

1. Dashboard passes `include_self=true` when querying own-agent readout.
2. Add separate `/api/agents/:id/presence` endpoint that always includes self.
3. Flip default to `includeSelf=true` for non-cross-agent UI consumers.

## Env

- macOS Darwin 25.4.0
- harness: claude-code
- signetai 0.108.9 via bun

### PR DESCRIPTION
**Pull request by NicholaiVogel**
## Summary

Fixes #568.

The dashboard home readout now fetches live own-agent presence with `include_self=true` and uses that data for `PROJECT` and `LAST SEEN`. The existing continuity data remains as a fallback when presence is unavailable.

This keeps `/api/cross-agent/presence` peer-oriented by default for cross-agent consumers, while making the dashboard explicit about wanting the current agent's own sessions.

## Validation

- `bun test surfaces/dashboard/src/lib/agent-presence.test.js`
- `bunx biome check surfaces/dashboard/src/lib/agent-presence.ts surfaces/dashboard/src/lib/agent-presence.test.js`
- `bun run check` in `surfaces/dashboard` after `bun run build:core`
- `bun run build` in `surfaces/dashboard`

`bun run check` and `bun run build` still report existing Svelte accessibility/deprecation warnings in unrelated dashboard files, but complete successfully.

### CODE REVIEW

**Comment by PR-Reviewer-Ant** [comment]
Hi @NicholaiVogel - I'm an automated code reviewer powered by [pr-reviewer](https://github.com/NicholaiVogel/pr-reviewer). I'm taking a look at the fixes in `fix(dashboard): show own-agent presence in readout` (commit `c3980619`) now and I'll follow up shortly with feedback.

File: surfaces/dashboard/src/lib/components/home/AgentHeader.svelte [hunk 1]
```diff
@@ -41,9 +44,19 @@ const ageLabel = $derived.by(() => {
 const activeSessions = $derived(daemonStatus?.activeSessions ?? 0);
 const version = $derived(daemonStatus?.version ?? "--");
 
+const latestPresence = $derived.by(() => {
```
Comment (PR-Reviewer-Ant) [inline surfaces/dashboard/src/lib/components/home/AgentHeader.svelte]: Blocking: `latestPresence` picks the most recent session across all returned presence entries, but does not filter to the current agent. If `/api/cross-agent/presence?include_self=true` returns peers + self, `PROJECT` and `LAST SEEN` can reflect a peer instead of the active agent, which diverges from the PR’s stated behavior.

**Review by PR-Reviewer-Ant — COMMENTED** [review]
> Automated review by [pr-reviewer](https://github.com/NicholaiVogel/pr-reviewer) | model: gpt-5.3-codex | commit: `c3980619`

[Automated Review by pr-reviewer] Found a behavior mismatch with the PR goal: the new readout path does not ensure it is using the current agent’s own presence data.

**Confidence:** Medium [sufficient_diff_evidence, targeted_context_included, ambiguous_requirements] - In AgentHeader, `latestPresence` is selected from the full `presence` array by newest `lastSeenAt` without filtering to the current agent. Given the endpoint is `/api/cross-agent/presence` and `include_self=true` typically means 'include self in addition to peers', the dashboard can display another agent’s project/last-seen when that session is newer. This directly conflicts with the stated own-agent readout intent.

> **Note:** This PR touches UI files but no screenshots were referenced in the description. Consider adding visual previews for reviewers.

File: surfaces/dashboard/src/lib/agent-presence.test.js [hunk 2]
```diff
@@ -0,0 +1,56 @@
...
+describe("agent presence api helpers", () => {
+	it("builds an own-agent readout URL that includes self sessions", () => {
+		const url = new URL(buildOwnAgentPresenceUrl("http://localhost:3850", 10));
+
+		expect(url.pathname).toBe("/api/cross-agent/presence");
+		expect(url.searchParams.get("include_self")).toBe("true");
+		expect(url.searchParams.get("limit")).toBe("10");
+	});
+
+	it("includes own-agent sessions for the dashboard readout", async () => {
```
Comment (PR-Reviewer-Ant) [inline surfaces/dashboard/src/lib/agent-presence.test.js]: Test coverage gap: the new tests verify `include_self=true` but do not cover mixed peer/self responses. Add a case proving readout selection is constrained to the current agent when peer sessions are newer.

File: surfaces/dashboard/src/lib/agent-presence.ts [hunk 3]
```diff
@@ -0,0 +1,50 @@
+export const DEFAULT_AGENT_ID = "default";
```
Comment (PR-Reviewer-Ant) [inline surfaces/dashboard/src/lib/agent-presence.ts]: Blocking: own-agent scoping is hardcoded to `"default"` (`DEFAULT_AGENT_ID`) and propagated through URL building/fetch/selection. That does not reliably represent the *current* agent and can show wrong `PROJECT`/`LAST SEEN` when the active agent ID differs. Pass the runtime/current agent ID from identity/daemon state into `getOwnAgentPresence` and `selectLatestOwnPresence` instead of relying on a fixed constant.

**Review by PR-Reviewer-Ant — CHANGES_REQUESTED** [review]
> Automated review by [pr-reviewer](https://github.com/NicholaiVogel/pr-reviewer) | model: gpt-5.3-codex | commit: `af0fac75`

[Automated Review by pr-reviewer] Found a blocking correctness issue in own-agent presence scoping; ready for human follow-up after fixes.

**Confidence:** Medium [sufficient_diff_evidence, targeted_context_included, ambiguous_requirements] - The new presence path hardcodes `agent_id=default` via `DEFAULT_AGENT_ID` and all call sites/tests use that default. If the active agent is not `default`, the dashboard will query/select another agent’s sessions (or none), which conflicts with the PR claim of showing the current agent’s own presence. I can prove the hardcoded scope from the changed files, but cannot confirm from this diff alone whether non-default agent IDs are impossible in all runtime modes.
