### PR TITLE
fix(daemon): dedupe automatic hooks by runtime path

### LINKED ISSUE #536: perf(daemon): hook processing pipeline blocks event loop — 400+ warnings/day from synchronous transcript-fallback and duplicate harness calls
**Signet version:** 0.102.4
**Environment:** Linux 6.8.0-110-generic, Node v22.22.1, Bun 1.3.12
**Related issues:** #535 (reindexMemoryArtifacts cold-start, minor contributor)

---

## Summary

The hook processing pipeline (specifically `user-prompt-submit` hooks) is the dominant source of event loop blocking in the daemon. In a single day of normal operation, **595 hook callbacks** were processed with an average duration of **2.3 seconds** each and a peak of **6 seconds**. This produced **413 `Event loop blocked` warnings**. Two compounding factors make it worse: (1) the `transcript-fallback` engine takes 5–6 seconds per call, and (2) every prompt fires hooks for **both `claude-code` and `opencode` harnesses** on the same session, doubling the work.

---

### Hook processing duration

595 `User prompt submit` hook callbacks were logged in one day:

```
count=595  min=2ms  median=2204ms  p90=4341ms  p99=5644ms  max=5986ms  avg=2279ms
```

### Engine breakdown

| Engine | Count | Typical duration |
|---|---|---|
| `transcript-fallback` | 403 (68%) | 5,000–6,000ms |
| `temporal-fallback` | 163 (27%) | ~500–2,000ms |
| `low-confidence` | 31 (5%) | 600–800ms |
| `no-query` | 2 (<1%) | — |

The `transcript-fallback` engine dominates both in frequency and per-call cost.

### Duplicate harness processing

Every prompt fires hooks for both harness identifiers even though it is a single session:

```
122 calls  harness=opencode   session=ses_2560446cfffesnEr3PWjY6KmDb
122 calls  harness=claude-code session=ses_2560446cfffesnEr3PWjY6KmDb  ← same session

28 calls   harness=opencode   session=ses_2554da0f9ffeCbueOOjPSZL41P
28 calls   harness=claude-code session=ses_2554da0f9ffeCbueOOjPSZL41P  ← same session
```

This means **every prompt is processed twice** — doubling memory search, transcript retrieval, and injection work.

### Resulting event loop blocking

413 `Event loop blocked` warnings in one day:

```
count=407  min=102ms  median=1255ms  p90=3645ms  p99=6293ms  max=44300184ms  avg=110517ms
```

(The 44.3M ms outlier is a system suspend; excluding it: median=1,255ms, avg=1,713ms)

**Hourly distribution** (correlates with user prompt activity):

| Hour | Blocked events | Hook calls |
|---|---|---|
| 08:xx | 58 | ~80 |
| 09:xx | 71 | ~90 |
| 10:xx | 171 | ~200 |
| 11:xx | 75 | ~110 |
| 12:xx | 5 | ~15 |

### Burst pattern

Blocking events come in pairs/triples because a single prompt triggers:
1. `claude-code` harness hook (2–6s)
2. `opencode` harness hook (2–6s)
3. Summary worker fact insertion (concurrent)
4. Transcript queuing (concurrent)

All compete for the event loop within the same second window.

---

## Expected Behavior

1. A single prompt should fire hooks for **one** harness, not two.
2. Hook processing (especially memory search and transcript retrieval) should not block the event loop for >100ms.
3. The `transcript-fallback` engine should either be async or off-loaded from the main thread.

---

## Steps to Reproduce

1. Run the daemon with an active OpenCode session (which registers as both `opencode` and `claude-code` harness types).
2. Send prompts at normal conversational pace (~1 per minute).
3. Grep the log file:
   ```bash
   grep '"Event loop blocked"' ~/.agents/.daemon/logs/signet-$(date +%Y-%m-%d).log | wc -l
   grep '"User prompt submit"' ~/.agents/.daemon/logs/signet-$(date +%Y-%m-%d).log | wc -l
   ```
4. The blocked count will track closely with the hook count.

---

## Root Cause Analysis

**Three independent issues compound:**

1. **Synchronous transcript-fallback engine** — The `transcript-fallback` engine performs memory search + transcript retrieval synchronously on the main thread. At 5–6 seconds per call with 403 calls/day, this is the single largest source of blocking.

2. **Duplicate harness registration** — OpenCode sessions register under both `opencode` and `claude-code` harness identifiers. The hook dispatcher treats these as separate harnesses and processes the same prompt twice. This doubles all hook work for every prompt.

3. **No batching or debouncing of concurrent hooks** — When multiple hooks fire within the same second (prompt-submit + session-end + summary-worker), they all run synchronously, creating multi-second blocking bursts.

---

## Suggested Fix

1. **Deduplicate harness hooks** — If the same `sessionKey` has already been processed for a prompt, skip the second harness callback. A simple `Set<string>` per prompt cycle would suffice.

2. **Make transcript-fallback async** — Move transcript retrieval and memory search to a worker or use `setImmediate()` between stages to yield control.

3. **Debounce hook bursts** — If multiple hooks arrive within a short window for the same session, batch them.

---

## Impact

- **413 event loop blocked warnings per day** — this is the dominant source of all blocking warnings in the daemon.
- **HTTP API latency spikes** — any request arriving during a 5–6s transcript-fallback call gets delayed.
- **Cumulative blocking** — 595 calls × 2.3s avg = ~23 minutes of total event loop blocking per day.
- **Monitoring noise** — 413 warnings/day trains operators to ignore blocking warnings, reducing diagnostic value.

---

## Workaround

No workaround. The duplicate harness processing is structural.

---

## Environment Details

- **Signet:** 0.102.4
- **OS:** Ubuntu, Linux 6.8.0-110-generic
- **Node:** v22.22.1
- **Bun:** 1.3.12
- **DB:** SQLite (bun:sqlite)
- **Date observed:** 2026-04-20

### PR DESCRIPTION
**Pull request by NicholaiVogel**
## Summary

- make automatic hook processing claim session runtime ownership server-side and skip conflicting runtime callbacks with 200 no-op responses
- keep explicit `remember` and `recall` strict so real user-initiated memory actions still surface runtime conflicts
- add short-lived session-end tombstones so duplicate end hooks cannot reprocess a session after the owning runtime releases its live claim
- mark legacy CLI hooks with `runtimePath: "legacy"` in both body and `x-signet-runtime-path` headers
- disable synchronous transcript scan fallback on the prompt hot path while preserving indexed FTS transcript fallback

## Root cause

Issue #536 came from two compounding hot-path failures. OpenCode/plugin and legacy hook paths could both process the same `sessionKey`, because mid-session automatic hooks only checked an existing owner and did not claim unowned sessions. Legacy CLI hooks also did not consistently identify themselves as the legacy runtime path. When both paths ran, prompt-submit duplicated memory search and transcript fallback work. The transcript fallback path could then drop into a synchronous `LIKE` scan when FTS was unavailable or failed, which made the duplicate work much more expensive.

## Impact

Automatic lifecycle hooks now have one owner per session. Duplicate runtime callbacks are acknowledged as successful no-ops instead of doing duplicate memory work or creating harness-visible 409s. Existing setups should continue working because requests without a `sessionKey` or without a runtime marker retain the previous behavior, same-runtime repeated calls refresh the owner, and explicit `remember`/`recall` conflict behavior is unchanged.

Closes #536.

## Validation

- `bun test packages/cli/src/commands/hook.test.ts packages/daemon/src/hooks-recall.test.ts packages/daemon/src/hooks.prompt-submit.test.ts packages/daemon/src/session-tracker.test.ts`
- `bunx biome check packages/daemon/src/session-tracker.ts packages/daemon/src/session-tracker.test.ts packages/daemon/src/routes/hooks-routes.ts packages/daemon/src/hooks-recall.test.ts packages/daemon/src/hooks.ts packages/daemon/src/session-transcripts.ts packages/daemon/src/hooks.prompt-submit.test.ts packages/cli/src/commands/hook.ts packages/cli/src/commands/hook.test.ts`
- `git diff --check`
- `bun run typecheck`
- `bun run build`

Full `bun run lint` is currently blocked by unrelated repo-wide Biome formatting diagnostics in existing files, mostly package manifests. Changed-file Biome validation passes.

### CODE REVIEW

**Comment by PR-Reviewer-Ant** [comment]
Hi @NicholaiVogel - I'm an automated code reviewer powered by [pr-reviewer](https://github.com/NicholaiVogel/pr-reviewer). I'm taking a look at the fixes in `fix(daemon): dedupe automatic hooks by runtime path` (commit `b8b4a876`) now and I'll follow up shortly with feedback.

File: packages/daemon/src/routes/hooks-routes.ts [hunk 1]
```diff
@@ -108,6 +110,68 @@ function checkSessionClaim(
...
+	const claim = claimSession(sessionKey, runtimePath, agentId);
+	if (claim.ok) return null;
+
+	logger.info("hooks", "Duplicate runtime hook skipped", {
+		hook,
+		sessionKey,
+		runtimePath,
+		claimedBy: claim.claimedBy,
+	});
+	return {
```
Comment (PR-Reviewer-Ant) [inline packages/daemon/src/routes/hooks-routes.ts:131]: Blocking: `skipConflictingSessionEnd` short-circuits on any ended-session tombstone even when `runtimePath` is missing. Combined with `claimAutomaticSessionOrSkip` requiring `runtimePath` to claim, unmarked clients can have valid `session-end` calls skipped for up to 30 minutes if they reuse a `sessionKey`. This diverges from the PR description’s compatibility claim that requests without runtime markers retain previous behavior and risks dropping memory extraction for those clients.

**Review by PR-Reviewer-Ant — COMMENTED** [review]
> Automated review by [pr-reviewer](https://github.com/NicholaiVogel/pr-reviewer) | model: gpt-5.3-codex | commit: `b8b4a876`

[Automated Review by pr-reviewer] Found one blocking behavioral regression against the PR’s backward-compatibility claim.

**Confidence:** High [sufficient_diff_evidence, targeted_context_included] - The new session-end dedupe path in hooks-routes checks tombstones before runtime-path validation, while automatic claim logic only runs when a runtime path is present. This creates a concrete skip path for unmarked requests that previously processed normally, directly contradicting the stated 'without a runtime marker retain previous behavior' claim.
