### PR TITLE
fix(daemon): preserve multiline markdown for embeddings

### LINKED ISSUE #418: Flattened Session Logs markdown tables cause Ollama embedding 500s and repeated daemon warning spam
**Signet version:** 0.90.0
**Environment:** Windows 10.0.26200.8037, Node v25.5.0, Bun 1.3.11
**Related issues:** N/A

---

## Summary

openclaw-memory can generate a Session Logs fact whose markdown table is flattened onto a single line before embedding. That payload reliably causes Ollama /api/embeddings to return HTTP 500 for mxbai-embed-large, which creates repeated Ollama embedding request failed warning spam in the daemon. This does not appear to be a general Ollama outage: direct embedding calls succeed for normal content and for the same table when preserved as multiline markdown.

---

## Observed Behavior

The daemon repeatedly logs embedding failures like this:

```json
{
  "timestamp": "2026-03-31T02:00:47.504Z",
  "level": "warn",
  "category": "embedding",
  "message": "Ollama embedding request failed",
  "data": {
    "status": 500,
    "model": "mxbai-embed-large"
  }
}
```

A concrete offending memory had this shape:

```json
{
  "id": "<memory-id>",
  "who": "openclaw-memory",
  "tags": "openclaw,memory-log,named,<REDACTED_BACKUP_NAME>,hierarchical-section",
  "created_at": "2026-03-31T01:56:51.692Z",
  "content": "## Session Logs The following sessions have been recorded: | id | kind | source | depth | session | project | ref | latest | |----|------|--------|-------|---------|----------|-----|--------| | <session-id> | session | summary | 0 | none | <REDACTED_PROJECT_PATH> | none | 2026-03-26T05:38:44.453Z | | <session-id> | session | summary | 0 | none | <REDACTED_PROJECT_PATH> | none | 2026-03-26T05:32:14.925Z | | <session-id> | session | summary | 0 | none | <REDACTED_PROJECT_PATH> | none | 2026-03-26T05:28:32.145Z | | <session-id> | session | summary | 0 | none | <REDACTED_PROJECT_PATH> | none | 2026-03-26T05:25:12.345Z | | <session-id> | session | summary | 0 | none | <REDACTED_PROJECT_PATH> | none | 2026-03-26T05:22:01.234Z | *Note: This table shows the 5 most recent sessions in chronological order (newest at the top).*"
}
```

Direct Ollama repro against the currently missing memories showed only the flattened Session Logs memory fails:

```
missing 5
<memory-id> 1052 ERR <HTTPError 500: 'Internal Server Error'> '## Session Logs The following sessions have been recorded: | id | kind | source | depth | session | project | ref | latest | |----|------|--------|-------|---------|----------|----'
<memory-id> 172 OK 1024 'Three PowerShell hook scripts implemented: ...'
<memory-id> 152 OK 1024 'Signet daemon exposes /api/hooks/pre-compaction, /api/hooks/compaction-complete, and /api/hooks/session-end endpoints for session lifecycle integration.'
<memory-id> 141 OK 1024 'Agent definition ... updated to document PreCompact and Stop hooks ...'
<memory-id> 117 OK 1024 'Signet daemon exposes /api/hooks/pre-compaction, /api/hooks/compaction-complete, and /api/hooks/session-end endpoints'
```

The same table content succeeds when reformatted as normal multiline markdown instead of a single line.

Current embedding health still reports the provider as reachable:

```json
{
  "status": "healthy",
  "config": {
    "provider": "ollama",
    "model": "mxbai-embed-large",
    "dimensions": 1024
  },
  "checks": [
    {
      "name": "provider-available",
      "status": "ok",
      "message": "ollama (mxbai-embed-large) is reachable"
    }
  ]
}
```

---

## Expected Behavior

Generated memories should not produce repeated embedding warning spam from a single poison-pill payload. Multiline markdown tables should either be preserved during ingest, normalized into a safe plain-text representation before embedding, or skipped/quarantined after a bounded number of failures.

---

## Steps to Reproduce

1. Import or regenerate a memory backup that contains a Session Logs section with a markdown table.
2. Let the ingest path produce a fact whose content is the entire table flattened onto one line with pipe delimiters.
3. Allow the embedding worker to process that memory with embedding.provider: ollama and model: mxbai-embed-large.
4. Observe repeated daemon warnings: Ollama embedding request failed with status: 500.
5. Send the same content directly to Ollama:
  - flattened single-line table -> HTTP 500
  - equivalent multiline markdown table -> succeeds

---

## Root Cause Analysis

The failure appears to originate before the embedding fetch layer, in content generation or normalization for imported memory/log sections.

Key observations:

- Ollama is healthy and reachable.
- Normal payloads embed successfully.
- The same semantic content succeeds when formatted with real newlines.
- The failing payload is a flattened single-line markdown table generated by openclaw-memory.
- The problem recurred after deleting one bad memory because a new row with the same source tag was regenerated.

Likely root cause:

- ingest/normalization flattens structured markdown table content into a single line;
- embedding worker retries the bad memory repeatedly instead of quarantining/skipping it.

---

## Suggested Fix

1. In ingest/normalization, preserve newline structure for markdown tables, or convert tables to safe plain-text bullets before embedding.

2. In the embedding worker, add poison-pill handling:
   - track repeated embedding failures per memory/content hash
   - after N failures, mark as skipped/quarantined instead of retrying forever
   - include memory id/content hash in logs for diagnosis

3. Optionally add a pre-embed sanitizer:
   - detect long single-line pipe-table payloads
   - rewrite them into multiline markdown or plain text before calling Ollama

---

## Impact

A single generated memory can cause ongoing daemon warning spam and make the system look like it has a provider-wide embedding outage. The issue can recur whenever the same backup/source content is re-imported.

---

## Workaround

Delete the offending generated memory row(s) whose content starts with:

## Session Logs The following sessions have been recorded:
In this case, deleting the bad generated rows stopped the spam until the bad source was re-imported.

Operational workaround:

prevent re-import of specific memory backup, or
rewrite the generated Session Logs fact into multiline markdown before embedding.
---

## Environment Details

Signet: 0.90.0
OS: Windows 10.0.26200.8037
Node: v25.5.0
Bun: 1.3.11
DB: SQLite
Date observed: 2026-03-30

### PR DESCRIPTION
**Pull request by NicholaiVogel**
## summary
- preserve multiline markdown in stored memory content so markdown tables are not flattened before embedding
- keep semantic normalization whitespace-insensitive for dedupe/hash parity across TS, native Rust, and daemon-rs
- add bounded embedding retry backoff plus regression coverage for issue #418

## testing
- bun run build:native
- bun test packages/daemon/src/content-normalization.test.ts packages/daemon/src/embedding-tracker.test.ts packages/daemon/src/embedding-fetch.test.ts
- cd packages/native && cargo test normalization
- cd packages/daemon-rs && cargo test -p signet-services normalize
- bun run typecheck
- bunx biome check docs/research/technical/RESEARCH-MARKDOWN-EMBEDDING-NORMALIZATION.md docs/specs/planning/markdown-embedding-normalization-hardening.md docs/specs/dependencies.yaml docs/specs/INDEX.md packages/daemon/src/content-normalization.ts packages/daemon/src/content-normalization.test.ts packages/daemon/src/embedding-tracker.ts packages/daemon/src/embedding-tracker.test.ts

## notes
- adds an incident-driven research/spec planning stub per repo protocol before implementation
- full repo lint and spec-deps-check still report unrelated pre-existing failures outside this change

closes #418

### CODE REVIEW

**Comment by PR-Reviewer-Ant** [comment]
Hi @NicholaiVogel - I'm an automated code reviewer powered by [pr-reviewer](https://github.com/NicholaiVogel/pr-reviewer). I'm taking a look at the fixes in `fix(daemon): preserve multiline markdown for embeddings` (commit `5feceebd`) now and I'll follow up shortly with feedback.

File: packages/daemon/src/embedding-tracker.ts [hunk 1]
```diff
@@ -80,11 +93,18 @@ export function startEmbeddingTracker(
 			const staleRows = accessor.withReadDb((db) => {
 				return listStaleEmbeddingRows(db, embeddingCfg.model, trackerCfg.batchSize) as StaleRow[];
 			});
+			const now = Date.now();
```
Comment (PR-Reviewer-Ant) [inline packages/daemon/src/embedding-tracker.ts]: The new suppression cache is keyed only by `row.id`, so a failure on one content version suppresses retries for any later content on the same memory row. If the user edits or reimports the memory and `contentHash` changes, `readyRows` will still skip it until the old backoff expires even though the poison-pill payload is gone. Key this state by at least `(row.id, row.contentHash, embedding model)` or clear the failure entry when the hash changes.

File: packages/daemon/src/embedding-tracker.test.ts [hunk 2]
```diff
@@ -0,0 +1,16 @@
+import { describe, expect, it } from "bun:test";
```
Comment (PR-Reviewer-Ant) [inline packages/daemon/src/embedding-tracker.test.ts:1]: The PR description and planning stub both claim retry-suppression hardening, but the new tests only cover the pure backoff helper. There is no regression test proving that the tracker actually suppresses repeated attempts across cycles, clears suppression on success, or avoids suppressing a new `contentHash` for the same memory id. That leaves the main incident path unguarded.

**Review by PR-Reviewer-Ant — CHANGES_REQUESTED** [review]
> Automated review by [pr-reviewer](https://github.com/NicholaiVogel/pr-reviewer) | model: gpt-5.4 | commit: `5feceebd`

[Automated Review] Found one blocking logic issue in the retry suppression path and one notable test gap against the PR's stated goals.

**Confidence:** Medium [sufficient_diff_evidence, targeted_context_included, missing_runtime_repro] - The retry suppression state in `packages/daemon/src/embedding-tracker.ts` is keyed only by `row.id`, while the same code logs and writes against `contentHash`. From the diff alone, a failed payload for one version of a memory will suppress retries for later content changes on that same memory id until the backoff expires. I can prove that from the introduced map keying and filter logic, but I did not run the daemon to reproduce the exact stale-row lifecycle.

**Review by PR-Reviewer-Ant — COMMENTED** [review]
> Automated review by [pr-reviewer](https://github.com/NicholaiVogel/pr-reviewer) | model: gpt-5.4 | commit: `9003203c`

[Automated Review] No new blocking issues found in the current diff; this looks ready for human review.

**Confidence:** Medium [sufficient_diff_evidence, targeted_context_included, missing_runtime_repro] - I validated the PR description against the current diff: storage normalization now preserves line breaks in the TS, native Rust, and daemon-rs normalization paths, and the retry suppression logic is now keyed by memory id + content hash + model with regression tests covering the previously flagged same-id/new-hash case. I did not run the daemon or inspect a live embedding cycle, so runtime-only behavior such as tracker shutdown timing and provider-specific failure handling was not reproduced here.
