### PR TITLE
fix: static identity fallback when daemon is unreachable

### LINKED ISSUE #219: Session-start hook should fall back to static identity files when daemon is unreachable
## Problem

When the Signet daemon isn't running (e.g., after a machine reboot without a launchd/systemd service), the `session-start` hook fails silently within its timeout window. For harnesses like Claude Code, this means the session starts with zero identity context — no personality, no memory, no user profile.

Previously, `~/.claude/CLAUDE.md` contained a full copy of all identity files as a safety net. But this caused ~6,800 tokens of duplication per session (identity loaded from both CLAUDE.md and the daemon hook). The recommended fix was to remove CLAUDE.md and let the daemon be the sole injector — but this creates a single point of failure.

## Expected Behavior

When the session-start hook cannot reach the daemon (connection refused, timeout, etc.), it should fall back to reading the identity files directly from the agents directory:

- `AGENTS.md`
- `SOUL.md`
- `IDENTITY.md`
- `USER.md`
- `MEMORY.md`

This provides degraded but functional context (no live memory search or scoring, but core identity and working memory are present). The hook could also inject a notice like `[signet: daemon offline — running with static identity]` so the user/agent knows the session is degraded.

## Context

- Related to the CLAUDE.md duplication issue noted in the connector source (`"CLAUDE.md generation removed — identity content is injected via session-start hooks"`)
- Related to extraction pipeline Bug 3 in #156 (CLAUDE.md contaminating extraction calls was another reason to remove it)
- A launchd service can mitigate this, but doesn't cover all platforms or failure modes

### PR DESCRIPTION
**Pull request by NicholaiVogel**
## Summary

Closes #219.

- When the daemon isn't running during session-start, hooks now read identity files (AGENTS.md, SOUL.md, IDENTITY.md, USER.md, MEMORY.md) directly from `~/.agents/` instead of returning empty context
- Adds `readStaticIdentity()` to `@signet/core` with budget-enforced file reading matching daemon inject budgets
- Wired into CLI hooks (covers Claude Code + Codex), OpenCode plugin, and OpenClaw adapter
- Injects `[signet: daemon offline — running with static identity]` notice so the agent knows it's running degraded
- 7 tests covering missing dirs, partial files, budget truncation, and empty file skipping

## Test plan

- [x] `bun test packages/core/src/__tests__/identity.test.ts` — 7/7 pass
- [x] `bun run build` — clean
- [x] `bun run typecheck` — clean (pre-existing opencode-plugin error unrelated)
- [ ] Manual: stop daemon, run `signet hook session-start -H claude-code --project .` — verify identity output
- [ ] Manual: start daemon, run same command — verify full daemon response (no regression)

### CODE REVIEW

**Comment by NicholaiVogel** [comment]
Hi @NicholaiVogel - I'm @NicholaiVogel's PR-reviewing agent powered by [pr-reviewer](https://github.com/NicholaiVogel/pr-reviewer). I'm taking a look at the fixes in `fix: static identity fallback when daemon is unreachable` (commit `3f306802`) now and I'll follow up shortly with feedback.

File: packages/adapters/openclaw/src/index.ts [hunk 1]
```diff
@@ -353,6 +356,42 @@ export async function isDaemonRunning(daemonUrl = DEFAULT_DAEMON_URL): Promise<b
 	}
 }
 
+// ============================================================================
+// Static identity fallback when daemon is unreachable
+// ============================================================================
+
+const STATIC_FILES: ReadonlyArray<{ file: string; header: string; budget: number }> = [
```
Comment (NicholaiVogel) [inline packages/adapters/openclaw/src/index.ts]: **Budget triplication / drift risk.** `STATIC_FILES` and `readStaticIdentity()` are copied verbatim from `@signet/core` rather than imported. Identical copies also exist in `packages/opencode-plugin/src/index.ts`. If the character budgets in `packages/core/src/identity.ts` are updated, the two adapter copies will silently stay out of sync and produce differently-truncated output. Since `@signet/core` already exports `readStaticIdentity(agentsDir)`, the openclaw adapter should import and call that instead of maintaining a local copy. The main difference (returning `SessionStartResult | null` vs `string | null`) is just a thin wrapper:
```ts
// instead of the local readStaticIdentity()
import { readStaticIdentity } from "@signet/core";
// ...
const inject = readStaticIdentity(dir);
if (!inject) return null;
return { identity: { name: "signet" }, memories: [], inject };
```

File: packages/opencode-plugin/src/index.ts [hunk 2]
```diff
@@ -73,6 +76,38 @@ function readRuntimeEnv(name: string): string | undefined {
 	return typeof value === "string" ? value : undefined;
 }
 
+// ============================================================================
+// Static identity fallback when daemon is unreachable
+// ============================================================================
+
```
Comment (NicholaiVogel) [inline packages/opencode-plugin/src/index.ts:82]: Same triplication as the openclaw adapter — `STATIC_FILES` and `readStaticIdentity()` are local copies of the `@signet/core` implementation. If this package cannot import from `@signet/core` due to dependency constraints, that constraint should be documented; otherwise, import `readStaticIdentity` from core and drop the local copy.

File: packages/cli/src/cli.ts [hunk 3]
```diff
@@ -5325,7 +5326,17 @@ hookCmd
 		});
 
 		if (!data) {
-			process.stderr.write("[signet] daemon not running, hook skipped\n");
+			const fallback = readStaticIdentity(AGENTS_DIR);
```
Comment (NicholaiVogel) [inline packages/cli/src/cli.ts:5329]: **Possible shape mismatch in JSON output.** When the daemon is online, the hook outputs the full daemon `SessionStartResult` JSON (which includes `identity`, `memories`, `inject`, etc.). When using the static fallback with `--json`, only `{ inject: string }` is emitted. Any caller that parses the full shape — e.g. inspecting `data.identity.name` or `data.memories` — will see `undefined` on the fallback path. If Claude Code or Codex hooks only consume `inject` this is fine, but it should be verified and, if needed, the fallback should pad the missing fields (`identity: { name: "signet" }, memories: []`) to match the daemon contract.

File: packages/core/src/__tests__/identity.test.ts [hunk 4]
```diff
@@ -0,0 +1,83 @@
...
+		// IDENTITY.md has a 2KB budget
+		const large = "x".repeat(3000);
+		writeFileSync(join(TMP, "IDENTITY.md"), large);
+
+		const result = readStaticIdentity(TMP);
+		expect(result).not.toBeNull();
+		expect(result).toContain("[truncated]");
+		// Should contain exactly 2000 chars of content + truncation marker
+		expect(result).toContain("x".repeat(2000));
+		expect(result).not.toContain("x".repeat(2001));
```
Comment (NicholaiVogel) [inline packages/core/src/__tests__/identity.test.ts:55]: Minor: the comment says "2KB budget" but `IDENTITY.md`'s budget is `2_000` characters, not 2048 bytes. Not a bug (the assertion correctly uses `x.repeat(2000)`), but the comment could mislead future maintainers who then set a budget in bytes.

**Comment by NicholaiVogel** [comment]
Both points addressed in eac1d78d:

**Duplication** — opencode-plugin and openclaw adapter now import \`readStaticIdentity\` from \`@signet/core\` instead of inlining their own copies. The adapters keep thin local wrappers only to handle their runtime-specific env access patterns (\`readRuntimeEnv\` in opencode-plugin for safety in non-standard runtimes, \`process.env\` in openclaw). Budget changes in core will now propagate automatically.

**CLI JSON shape** — \`--json\` fallback output now matches the full \`SessionStartResult\` shape: \`{ inject, identity: { name: "signet" }, memories: [] }\`. Callers that depend on \`identity\` or \`memories\` fields won't break.

**Comment by NicholaiVogel** [comment]
Hi @NicholaiVogel - quick follow-up pass on `fix: static identity fallback when daemon is unreachable` (commit `eac1d78d`); taking another look at the fixes and I will report back shortly.

File: packages/core/src/identity.ts [hunk 5]
```diff
@@ -301,6 +301,46 @@ export function getMissingIdentityFiles(basePath: string): string[] {
 	return missing;
 }
 
+/**
+ * Character budgets for static identity fallback, matching daemon inject budgets.
+ */
+const STATIC_BUDGETS: ReadonlyArray<{ file: string; header: string; budget: number }> = [
+	{ file: "AGENTS.md", header: "Agent Instructions", budget: 12_000 },
+	{ file: "SOUL.md", header: "Soul", budget: 4_000 },
```
Comment (NicholaiVogel) [inline packages/core/src/identity.ts:309]: Minor: `HEARTBEAT.md` and `TOOLS.md` are present in `IDENTITY_FILES` but intentionally excluded from `STATIC_BUDGETS`. This is fine (transient/optional files), but a brief comment explaining the omission would prevent a future contributor from wondering whether it was an oversight.
