### PR TITLE
fix: add migration for missing embeddings.vector column on older DBs

### LINKED ISSUE #221: fix: embeddings table missing 'vector' column on older DBs causes silent 500 in signet embed backfill
### Environment
- signetai: `0.60.0`
- Node.js: `v25.6.1` (bun:sqlite paths may differ)
- Ollama embedding provider: `nomic-embed-text` (768 dims)
- DB created on an older Signet version, upgraded in-place to 0.60.0

---

### What happened

Running `signet embed backfill` fails silently with a confusing error:

```
- Backfilling embeddings...
<anonymous_script>:1
Internal Server Error
^
SyntaxError: Unexpected token 'I', "Internal S"... is not valid JSON
```

The CLI crashes because `/api/repair/re-embed` returns HTTP 500 with `text/plain` body `"Internal Server Error"` instead of JSON, and the CLI tries to `JSON.parse()` the response unconditionally.

---

### Root cause

The `embeddings` table on DBs created before the `vector` column was added is missing that column:

```sql
-- Actual schema on affected DB
CREATE TABLE embeddings (
  id TEXT PRIMARY KEY,
  content_hash TEXT NOT NULL UNIQUE,
  dimensions INTEGER NOT NULL,
  source_type TEXT NOT NULL,
  source_id TEXT NOT NULL,
  chunk_text TEXT NOT NULL,
  created_at TEXT NOT NULL
  -- no 'vector' column!
);
```

But `reembedMissingMemories` in `packages/daemon/src/` does:

```sql
INSERT INTO embeddings
  (id, content_hash, vector, dimensions, source_type, source_id, chunk_text, created_at)
  VALUES (?, ?, ?, ?, 'memory', ?, ?, ?)
  ON CONFLICT(content_hash) DO UPDATE SET vector = excluded.vector ...
```

This throws `table embeddings has no column named vector`, the daemon catches it as an unhandled exception and returns 500, and the CLI blows up trying to parse the non-JSON response.

---

### Fix

Two changes needed:

**1. Add a migration in `packages/core/src/database.ts`** to add `vector BLOB` to the `embeddings` table if it doesn't exist:

```typescript
// In the migrations array, add something like:
{
  version: 32, // or next available
  name: 'embeddings-vector-column',
  up: (db) => {
    const cols = db.prepare("PRAGMA table_info(embeddings)").all() as any[];
    if (!cols.some(c => c.name === 'vector')) {
      db.exec("ALTER TABLE embeddings ADD COLUMN vector BLOB");
    }
  }
}
```

**2. Make the CLI handle non-JSON 500 responses gracefully** in the `embed backfill` action (instead of crashing on `JSON.parse`):

```typescript
// In secretApiCall or the backfill action handler:
if (!res.ok) {
  const text = await res.text();
  return { ok: false, data: { error: text || 'Request failed' } };
}
const data = await res.json();
```

---

### Workaround (confirmed working)

```bash
signet stop
sqlite3 ~/.agents/memory/memories.db "ALTER TABLE embeddings ADD COLUMN vector BLOB;"
signet start
signet embed backfill  # now works
```

---

### Additional context

This affects any user who:
1. Created their Signet DB on an older version (before `vector` was added to the `embeddings` schema)
2. Upgraded `signetai` in-place without a full DB wipe

The daemon's schema migration system in `packages/core/src/database.ts` should handle this automatically on startup.

### PR DESCRIPTION
**Pull request by NicholaiVogel**
## Summary

- Adds migration 032 to `ALTER TABLE embeddings ADD COLUMN vector BLOB` for databases created before the vector column existed — fixes silent 500 on `signet embed backfill`
- Hardens the CLI's `secretApiCall` to gracefully parse non-JSON error responses instead of crashing with `SyntaxError`

## Root Cause

Databases created on older Signet versions lack the `vector` column on `embeddings`. The daemon's `reembedMissingMemories` INSERT references that column, throws an unhandled SQLite error, returns HTTP 500 with plain text body, and the CLI crashes trying to `JSON.parse("Internal Server Error")`.

## Changes

| File | Change |
|------|--------|
| `packages/core/src/migrations/032-embeddings-vector-column.ts` | New migration: adds `vector BLOB` column if missing (no-op if table doesn't exist yet) |
| `packages/core/src/migrations/index.ts` | Register migration 032 |
| `packages/cli/src/cli.ts` | `secretApiCall` now reads response as text first, tries JSON.parse, falls back to `{ error: text }` |

## Test plan

- [x] All 18 migration tests pass (including the v1-stamped-DB upgrade path)
- [x] Core package builds and typechecks clean
- [x] New migration file passes biome lint
- [ ] Manual: create DB without vector column, run `signet embed backfill`, confirm it works
- [ ] Manual: trigger a non-JSON 500 from daemon, confirm CLI shows error message instead of crashing

Closes #221

### CODE REVIEW

**Comment by NicholaiVogel** [comment]
Hi @NicholaiVogel - I'm @NicholaiVogel's PR-reviewing agent powered by [pr-reviewer](https://github.com/NicholaiVogel/pr-reviewer). I'm taking a look at the fixes in `fix: add migration for missing embeddings.vector column on older DBs` (commit `bafab25f`) now and I'll follow up shortly with feedback.

File: packages/core/src/migrations/index.ts [hunk 1]
```diff
@@ -319,6 +320,11 @@ export const MIGRATIONS: readonly Migration[] = [
 			],
 		},
 	},
+	{
```
Comment (NicholaiVogel) [inline packages/core/src/migrations/index.ts:328]: Migration 032 doesn't declare an `artifacts` entry for `{ table: "embeddings", column: "vector" }`. Every other column-adding migration (e.g. v4, v5, v6, v17…) includes this so that `verifyArtifacts` confirms the DDL ran and `repairPhantomMigrations` can detect a phantom later. The early-exit on `cols.length === 0` makes verification safe (the table exists by the time this runs on non-fresh DBs). Consider adding:
```ts
artifacts: {
  columns: [{ table: "embeddings", column: "vector" }],
},
```

File: packages/core/src/migrations/032-embeddings-vector-column.ts [hunk 2]
```diff
@@ -0,0 +1,17 @@
...
+/**
+ * Migration 032: Ensure embeddings.vector column exists
+ *
+ * Databases created on older Signet versions may lack the `vector BLOB`
+ * column on `embeddings`. Without it, `reembedMissingMemories` throws
+ * "table embeddings has no column named vector" and the daemon returns
+ * an unhandled 500 to the CLI.
+ */
+export function up(db: MigrationDb): void {
+	const cols = db.prepare("PRAGMA table_info(embeddings)").all() as Array<{ name: string }>;
```
Comment (NicholaiVogel) [inline packages/core/src/migrations/032-embeddings-vector-column.ts:12]: The `cols.length === 0` early-exit is correct for a brand-new DB where baseline hasn't run yet, but it silently succeeds rather than failing. If somehow `embeddings` is absent on a DB that *should* have it (a phantom scenario), the migration passes and the problem goes undetected. This is an edge case the existing phantom-repair system would catch if an `artifacts` entry were declared — another reason to add one.

**Comment by NicholaiVogel** [comment]
Thanks for the review!

On the missing `artifacts` declaration for migration 032 — this was intentional rather than an oversight.

The `verifyArtifacts` function (migrations/index.ts:524) throws if a declared column's parent table doesn't exist at verification time:

```ts
if (!tables.has(col.table)) {
    throw new Error(
        `...declares column "${col.table}.${col.column}" but table does not exist`,
    );
}
```

Migration 032 is a repair migration with conditional execution: if `embeddings` doesn't exist yet (old DBs that had v1 stamped without running baseline fully), the `up()` function returns early. The post-DDL verifier would then throw on the artifact check even though the migration was correctly a no-op — baseline will create `embeddings` with `vector` when it runs.

Adding the artifact declaration with the current verifier causes the `"version 1 stamped by old inline migrate upgrades cleanly"` test to fail.

The fix options are:
1. **Keep as-is** — accept that repair migrations with conditional execution don't declare artifacts (reasonable tradeoff)
2. **Extend `MigrationArtifacts`** to support `optional: true` on column entries, allowing `verifyArtifacts` to skip the table-existence check — would make this consistent with other column-adding migrations

Happy to implement option 2 in this PR if you'd prefer. Otherwise I can open a separate issue for the migration framework enhancement and leave this as-is.

**Comment by NicholaiVogel** [comment]
Went ahead and implemented option 2. Added `optional?: boolean` to the `MigrationArtifacts` column type — when set, `verifyArtifacts` skips the table-existence check (but still verifies the column if the table does exist). Migration 032 now declares its artifact with `optional: true`, so phantom detection works and convention is maintained. All 18 migration tests pass.

**Comment by NicholaiVogel** [comment]
Hi @NicholaiVogel - quick follow-up pass on `fix: add migration for missing embeddings.vector column on older DBs` (commit `aced0f9f`); taking another look at the fixes and I will report back shortly.

File: packages/core/src/migrations/index.ts [hunk 3]
```diff
@@ -535,6 +549,9 @@ function verifyArtifacts(db: MigrationDb, migration: Migration): void {
 		const colCache = new Map<string, Set<string>>();
```
Comment (NicholaiVogel) [inline packages/core/src/migrations/index.ts:549]: Fixed from prior review: `verifyArtifacts` now correctly skips the table-missing check for `optional` columns. Behavior is sound — if the table exists but the column is absent the existing throw path still fires, so a partial ALTER failure won't silently pass verification. `findPhantomVersions` doesn't inspect `optional`, but that's fine here: by the time migration 032 is stamped, migration 001 has already created `embeddings`, so the table-missing branch in phantom detection is unreachable in practice.
