### PR TITLE
fix(daemon): normalize Claude Code transcript records

### LINKED ISSUE #280: normalizeJsonConversationRecord doesn't handle Claude Code JSONL format
## Bug

SessionEnd transcript extraction produces zero conversation turns for Claude Code sessions. The daemon logs `JSON-line transcript produced no conversation turns` even when a valid transcript with hundreds of KB is passed.

## Root Cause

`normalizeJsonConversationRecord` (daemon.js) handles three formats:
1. **Codex** — `type: "item.completed"`
2. **Event** — `type: "event_msg"`
3. **Generic** — top-level `role`

Claude Code uses none of these. Its JSONL records look like:

**User messages:**
```json
{"type": "user", "message": {"role": "user", "content": "Can you pull up the last ideation doc?"}, "uuid": "..."}
```

**Assistant messages:**
```json
{"message": {"role": "assistant", "content": [{"type": "thinking", "thinking": "..."}, {"type": "text", "text": "Here is..."}]}, "uuid": "..."}
```

**Non-conversation records:**
```json
{"type": "progress", "data": {"type": "hook_progress", ...}}
{"type": "file-history-snapshot", "snapshot": {...}}
```

The generic fallback at line ~34133 checks `extractString(record, ["role", "speaker"])` — but `role` is nested inside `record.message`, not at the top level. `extractString` only reads top-level keys.

Additionally, assistant `content` is an array of blocks (text, thinking, tool_use), not a string — so even if the path were correct, `extractString` would skip it.

Non-conversation records (`progress`, `file-history-snapshot`) pass `isRecord5` and count toward `parsedCount` but produce empty strings, so the transcript "succeeds" with zero useful content.

## Suggested Fix

Add a Claude Code branch before the generic role fallback:

```js
// Claude Code user: {type: "user", message: {role: "user", content: "..."}}
if (record.type === "user" && isRecord5(record.message)) {
  const text = extractString(record.message, ["content", "text"]);
  if (text) return `User: ${text}`;
}

// Claude Code assistant: {message: {role: "assistant", content: [...]}}
if (isRecord5(record.message) && extractString(record.message, ["role"]) === "assistant") {
  const content = record.message.content;
  if (typeof content === "string") return `Assistant: ${content}`;
  if (Array.isArray(content)) {
    const textParts = content
      .filter(b => b.type === "text" && typeof b.text === "string")
      .map(b => b.text.trim()).filter(Boolean);
    if (textParts.length > 0) return `Assistant: ${textParts.join(" ")}`;
  }
}

// Skip non-conversation Claude Code records
if (record.type === "progress" || record.type === "file-history-snapshot") return "";
```

## Verification

Patched locally and tested against a real 66-line Claude Code session transcript. Result: 14 conversation turns correctly extracted (all user + assistant messages). Previously: 0.

## Environment

- Signet v0.72.6
- Claude Code (claude-opus-4-6, 1M context)
- Harness: `claude-code`
- macOS (Darwin 25.3.0, arm64)

### PR DESCRIPTION
**Pull request by NicholaiVogel**
## Summary
- normalize Claude Code transcript records that store `role` under nested `message`
- extract assistant text from Claude Code block-array content
- add regression coverage for Claude Code conversation and non-conversation JSONL records

## Testing
- bun test packages/daemon/src/hooks.test.ts
- cd packages/daemon && bun run build

Fixes #280

### CODE REVIEW

**Comment by NicholaiVogel** [comment]
Hi @NicholaiVogel - I'm @NicholaiVogel's PR-reviewing agent powered by [pr-reviewer](https://github.com/NicholaiVogel/pr-reviewer). I'm taking a look at the fixes in `fix(daemon): normalize Claude Code transcript records` (commit `2c9fe048`) now and I'll follow up shortly with feedback.

File: packages/daemon/src/hooks.ts [hunk 1]
```diff
@@ -2282,6 +2288,22 @@ function extractString(record: Record<string, unknown>, keys: readonly string[])
...
+
+	const content = record.content;
+	if (!Array.isArray(content)) return "";
+
+	const parts = content.flatMap((item) => {
+		if (!isRecord(item) || item.type !== "text") return [];
+		const text = extractString(item, ["text", "content"]);
+		return text ? [text] : [];
+	});
+
```
Comment (NicholaiVogel) [inline packages/daemon/src/hooks.ts:2303]: Multi-block text arrays are joined with a single space (`parts.join(" ")`). This means an assistant response split across two text blocks — e.g. `["First paragraph.", "Second paragraph."]` — becomes `"First paragraph. Second paragraph."` with no paragraph boundary preserved. For memory-summary purposes this is fine, but worth documenting if this function is ever reused in a context where paragraph structure matters.

**Review by NicholaiVogel — COMMENTED** [review]
Clean, focused change that adds Claude Code transcript normalization. New `extractMessageText` helper correctly handles both string and array-format content. The `record.message` branch is correctly ordered before the `record.role` branch to prioritize the nested format. Regression tests cover the added paths including thinking-block filtering. No bugs, security issues, or logic errors found.

### Confidence: 8.8/10
- Style consistency & maintainability: 9
- Repository conventions adherence: 9
- Merge conflict detection confidence: 8
- Security vulnerability detection confidence: 9
- Injection risk detection confidence: 9
- Attack-surface risk assessment confidence: 9
- Future hardening guidance confidence: 7
- Scope alignment confidence: 10
- Existing functionality awareness: 9
- Existing tooling/pattern leverage: 9
- Functional completeness confidence: 9
- Pattern correctness confidence: 9
- Documentation coverage confidence: 8


```pr-review-confidence-json
{
  "style_maintainability": 9,
  "repo_convention_adherence": 9,
  "merge_conflict_detection": 8,
  "security_vulnerability_detection": 9,
  "injection_risk_detection": 9,
  "attack_surface_risk_assessment": 9,
  "future_hardening_guidance": 7,
  "scope_alignment": 10,
  "duplication_awareness": 9,
  "tooling_pattern_leverage": 9,
  "functional_completeness": 9,
  "pattern_correctness": 9,
  "documentation_coverage": 8
}
```
